import { saveSnapshot, getActiveSnapshot, saveNamedRoute, listSavedRoutes, deleteSavedRoute } from './storage.js';
const map = L.map('map').setView([45.9432, 24.9668], 7);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; OpenStreetMap contributors' }).addTo(map);
const mapElement = document.getElementById('map');
let reviewMap = null; let reviewMarkers = [];
const resizeMap = () => map.invalidateSize({ pan: false });
window.addEventListener('resize', resizeMap);
if (window.ResizeObserver) new ResizeObserver(resizeMap).observe(mapElement);
setTimeout(resizeMap, 150);
const state = { start: null, end: null, stops: [], markers: [], routeLayer: null, routeGeometry: null, routeId: '', editMode: false, undoStack: [], redoStack: [] };
let editingStopIndex = null;
let activeRecognition = null; let activeMicButton = null;
const $ = (selector) => document.querySelector(selector); const status = $('#status');
const STORAGE_KEY = 'route-optimizer-romania-v1';
const GEOCODE_CACHE_KEY = 'route-optimizer-geocode-cache-v1';
const ADDRESS_HISTORY_KEY = 'route-optimizer-address-history-v1'; const PREF_KEY = 'route-optimizer-preferences-v1';
function cleanPoint(point) { if (!point || !Number.isFinite(Number(point.lat)) || !Number.isFinite(Number(point.lon))) return null; return { ...point, lat: Number(point.lat), lon: Number(point.lon), display_name: String(point.display_name || point.input || 'Adresă') }; }
function cleanStops(stops) { return Array.isArray(stops) ? stops.map(cleanPoint).filter(Boolean).map((stop) => ({ ...stop, packageCount: Math.max(1, Number(stop.packageCount || 1)) })) : []; } function normalizeAddressText(value) { return String(value || '').normalize('NFD').replace(/\p{Diacritic}/gu, '').toLowerCase(); } function getBlockedRoads() { return String($('#blocked-roads')?.value || '').split(/[;,\n]/).map((part) => normalizeAddressText(part).trim()).filter((part) => part.length >= 3); } function blockedRoadMatch(point) { const text = normalizeAddressText(point?.display_name || point?.input || ''); return getBlockedRoads().find((road) => text.includes(road)) || ''; }
function snapshotState() { return JSON.parse(JSON.stringify({ start: state.start, end: state.end, stops: state.stops })); }
function restoreSnapshot(snapshot) { state.start = cleanPoint(snapshot?.start); state.end = cleanPoint(snapshot?.end); state.stops = cleanStops(snapshot?.stops); $('#start-address').value = state.start?.input || state.start?.display_name || ''; $('#end-address').value = state.end?.input || state.end?.display_name || ''; }
function pushUndo() { state.undoStack.push(snapshotState()); state.redoStack = []; if (state.undoStack.length > 20) state.undoStack.shift(); }
function undoLastChange() { const previous = state.undoStack.pop(); if (!previous) { setStatus('Nu există modificări de anulat.'); return; } state.redoStack.push(snapshotState()); restoreSnapshot(previous); invalidateOptimization(); saveState(); drawMarkers(); refreshList(); setStatus('Ultima modificare a fost anulată'); }
function redoLastChange() { const next = state.redoStack.pop(); if (!next) { setStatus('Nu există modificări de refăcut.'); return; } state.undoStack.push(snapshotState()); restoreSnapshot(next); invalidateOptimization(); saveState(); drawMarkers(); refreshList(); setStatus('Modificarea a fost refăcută'); }
function saveState() { const data = { routeId: state.routeId || '', start: state.start, end: state.end, stops: state.stops, routeGeometry: state.routeGeometry, routeDistance: state.routeDistance || 0, routeDuration: state.routeDuration || 0, returnToStart: $('#return-to-start').checked, serviceTime: $('#service-time').value, breakAfter: $('#break-after')?.value || '0', breakDuration: $('#break-duration')?.value || '15', departureTime: $('#departure-time').value, optimizationMode: $('#optimization-mode')?.value || 'balanced', vehicleProfile: $('#vehicle-profile')?.value || 'car', trafficLevel: $('#traffic-level')?.value || 'normal', vehicleCapacity: Math.max(1, Number($('#vehicle-capacity')?.value || 50)), roadAvoidance: $('#road-avoidance')?.value || 'none', blockedRoads: $('#blocked-roads')?.value || '' }; try { localStorage.setItem(STORAGE_KEY, JSON.stringify(data)); } catch { /* IndexedDB rămâne salvarea principală */ } saveSnapshot(data); }
function invalidateOptimization() { state.routeGeometry = null; state.routeDistance = 0; state.routeDuration = 0; state.stops.forEach((stop) => { delete stop.etaAt; delete stop.etaLabel; delete stop.lateMinutes; }); if (state.end) { delete state.end.etaAt; delete state.end.etaLabel; } if (state.routeLayer) { state.routeLayer.remove(); state.routeLayer = null; } const finish = $('#finish-route'); if (finish) finish.hidden = true; }
function loadPreferences() { try { const preferences = JSON.parse(localStorage.getItem(PREF_KEY) || '{}'); if (preferences.profile && $('#vehicle-profile')) $('#vehicle-profile').value = preferences.profile; if (preferences.capacity && $('#vehicle-capacity')) $('#vehicle-capacity').value = preferences.capacity; if (preferences.service !== undefined && $('#service-time')) $('#service-time').value = preferences.service; if (preferences.traffic && $('#traffic-level')) $('#traffic-level').value = preferences.traffic; } catch {} }function loadState() { try { const saved = JSON.parse(localStorage.getItem(STORAGE_KEY)); if (!saved) return; state.routeId = String(saved.routeId || ''); state.start = cleanPoint(saved.start); state.end = cleanPoint(saved.end); state.stops = cleanStops(saved.stops); state.routeGeometry = saved.routeGeometry || null; state.routeDistance = Number(saved.routeDistance || 0); state.routeDuration = Number(saved.routeDuration || 0); if (saved.returnToStart) $('#return-to-start').checked = true; if (saved.serviceTime !== undefined) $('#service-time').value = saved.serviceTime; if (saved.breakAfter !== undefined && $('#break-after')) $('#break-after').value = saved.breakAfter; if (saved.breakDuration !== undefined && $('#break-duration')) $('#break-duration').value = saved.breakDuration; if (saved.departureTime) $('#departure-time').value = saved.departureTime; if (saved.optimizationMode && $('#optimization-mode')) $('#optimization-mode').value = saved.optimizationMode; if (saved.vehicleProfile && $('#vehicle-profile')) $('#vehicle-profile').value = saved.vehicleProfile; if (saved.trafficLevel && $('#traffic-level')) $('#traffic-level').value = saved.trafficLevel; if (saved.vehicleCapacity !== undefined && $('#vehicle-capacity')) $('#vehicle-capacity').value = saved.vehicleCapacity; if (saved.roadAvoidance && $('#road-avoidance')) $('#road-avoidance').value = saved.roadAvoidance; if (saved.blockedRoads !== undefined && $('#blocked-roads')) $('#blocked-roads').value = saved.blockedRoads; if (state.start) $('#start-address').value = state.start.input || state.start.display_name; if (state.end) $('#end-address').value = state.end.input || state.end.display_name; } catch { localStorage.removeItem(STORAGE_KEY); } }
function formatDuration(totalMinutes) { const minutes = Math.max(0, Math.round(totalMinutes)); const hours = Math.floor(minutes / 60); const remainder = minutes % 60; if (!hours) return `${remainder} min`; if (!remainder) return `${hours} h`; return `${hours} h ${remainder} min`; }
function formatClock(timestamp) { return new Intl.DateTimeFormat('ro-RO', { hour: '2-digit', minute: '2-digit' }).format(new Date(timestamp)); }
async function fetchWithTimeout(url, options = {}, timeoutMs = 20000) { const controller = new AbortController(); const timeout = window.setTimeout(() => controller.abort(), timeoutMs); try { return await fetch(url, { ...options, signal: controller.signal }); } finally { window.clearTimeout(timeout); } }
async function fetchRoutingWithRetry(url, attempts = 2) { let lastError; for (let attempt = 0; attempt < attempts; attempt += 1) { try { const response = await fetchWithTimeout(url, {}, 20000); if (!response.ok) throw new Error(`Serviciul de rutare a răspuns cu ${response.status}.`); return response; } catch (error) { lastError = error; if (attempt + 1 < attempts) await new Promise((resolve) => setTimeout(resolve, 350 * (attempt + 1))); } } throw lastError || new Error('Serviciul de rutare nu răspunde.'); }
function setStatus(message, error = false) { status.textContent = message; status.style.background = error ? '#4a2525' : '#123b34'; status.style.color = error ? '#ffb4b4' : '#6ee7c8'; }
function refreshList() {
  const list = $('#stops-list'); list.innerHTML = '';
  const addTextRow = (className, label, point) => { if (!point) return; const item = document.createElement('li'); item.className = className; const strong = document.createElement('strong'); strong.textContent = label; const small = document.createElement('small'); small.textContent = point.display_name || point.input || ''; item.append(strong, small); list.append(item); };
  addTextRow('start-item', 'Plecare', state.start);
  state.stops.forEach((stop, index) => {
    const item = document.createElement('li'); item.className = 'stop-item';
    const content = document.createElement('div'); const title = document.createElement('strong'); title.textContent = String(index + 1) + '. ' + (stop.display_name || stop.input || 'Adresă');
    const details = document.createElement('small'); const parts = []; if (stop.group) parts.push('Grup: ' + stop.group); if (stop.windowStart || stop.windowEnd) parts.push('Fereastră ' + (stop.windowStart || '—') + '–' + (stop.windowEnd || '—')); parts.push(String(stop.serviceTime || 0) + ' min staționare'); parts.push(String(stop.packageCount || 1) + ' colete'); if (stop.etaLabel) parts.push('Sosire ' + stop.etaLabel); if (stop.lateMinutes) parts.push('Întârziat cu ' + stop.lateMinutes + ' min'); const blocked = blockedRoadMatch(stop); if (blocked) parts.push('⚠ Drum de verificat: ' + blocked); details.textContent = parts.join(' · '); content.append(title, details);
    const actions = document.createElement('span'); actions.className = 'stop-actions'; const edit = document.createElement('button'); edit.className = 'edit-stop'; edit.dataset.index = String(index); edit.title = 'Editează oprirea'; edit.setAttribute('aria-label', 'Editează oprirea ' + (index + 1)); edit.textContent = 'Editează'; const remove = document.createElement('button'); remove.className = 'remove-stop'; remove.dataset.index = String(index); remove.title = 'Șterge oprirea'; remove.setAttribute('aria-label', 'Șterge oprirea ' + (index + 1)); remove.textContent = '×'; actions.append(edit, remove); item.append(content, actions); list.append(item);
  });
  addTextRow('end-item', 'Final', state.end);
  $('#stop-count').textContent = state.stops.length; $('#summary').hidden = !state.stops.length; $('#optimize').disabled = !(state.start && state.stops.length);
  $('#review-route').hidden = !(state.start && state.stops.length);
  list.querySelectorAll('.remove-stop').forEach((button) => button.addEventListener('click', () => { if (!window.confirm('Ștergi această oprire din rută?')) return; pushUndo(); state.stops.splice(Number(button.dataset.index), 1); invalidateOptimization(); saveState(); drawMarkers(); refreshList(); setStatus('Oprire ștearsă'); }));
  list.querySelectorAll('.edit-stop').forEach((button) => button.addEventListener('click', () => { const index = Number(button.dataset.index); const stop = state.stops[index]; if (!stop) return; if (stop.locked) { setStatus('Stopul este blocat. Deblochează-l înainte de editare.', true); return; } editingStopIndex = index; $('#stop-address').value = stop.input || stop.display_name; $('#stop-address').focus(); setStatus('Editează adresa și apasă Adaugă'); }));
  renderRouteDetails();
  renderFeasibilityReport();
  enhanceStopList();
}

function enhanceStopList() { const list = $('#stops-list'); if (!list) return; list.querySelectorAll('.stop-item').forEach((item, index) => { const stop = state.stops[index]; if (!stop) return; item.draggable = !stop.locked; item.dataset.index = String(index); item.classList.toggle('stop-locked', Boolean(stop.locked)); item.addEventListener('dragstart', (event) => { if (stop.locked) { event.preventDefault(); return; } event.dataTransfer.setData('text/plain', String(index)); }); item.addEventListener('dragover', (event) => { if (!stop.locked) event.preventDefault(); }); item.addEventListener('drop', (event) => { event.preventDefault(); const from = Number(event.dataTransfer.getData('text/plain')); if (!Number.isInteger(from) || from === index || state.stops[from]?.locked || stop.locked) return; pushUndo(); const [moved] = state.stops.splice(from, 1); state.stops.splice(index, 0, moved); invalidateOptimization(); saveState(); drawMarkers(); refreshList(); setStatus('Stop mutat prin drag-and-drop'); }); if (!item.querySelector('.lock-stop')) { const actions = item.querySelector('.stop-actions'); const lock = document.createElement('button'); lock.className = 'lock-stop'; lock.type = 'button'; lock.dataset.index = String(index); lock.title = 'Blochează poziția'; lock.setAttribute('aria-label', (stop.locked ? 'Deblochează' : 'Blochează') + ' poziția stopului ' + (index + 1)); lock.textContent = stop.locked ? '🔒' : '🔓'; actions.prepend(lock); lock.addEventListener('click', () => { pushUndo(); stop.locked = !stop.locked; invalidateOptimization(); saveState(); refreshList(); setStatus(stop.locked ? 'Stop blocat' : 'Stop deblocat'); }); } }); }
function addPriorityControls() { const list = $('#stops-list'); if (!list) return; list.querySelectorAll('.stop-item').forEach((item, index) => { const stop = state.stops[index]; const actions = item.querySelector('.stop-actions'); if (!stop || !actions || actions.querySelector('.priority-input')) return; if (!stop.priority) stop.priority = 1; const input = document.createElement('input'); input.className = 'priority-input'; input.type = 'number'; input.min = '1'; input.max = '3'; input.step = '1'; input.value = String(stop.priority); input.title = 'Prioritate 1-3'; input.setAttribute('aria-label', `Prioritate stop ${index + 1}`); input.addEventListener('change', () => { pushUndo(); stop.priority = Math.max(1, Math.min(3, Number(input.value) || 1)); input.value = String(stop.priority); saveState(); setStatus('Prioritatea a fost salvată'); }); actions.prepend(input); }); }
function addWindowControls() {
  const list = $('#stops-list'); if (!list) return;
  list.querySelectorAll('.stop-item').forEach((item, index) => {
    const stop = state.stops[index]; if (!stop || item.querySelector('.window-controls')) return;
    const box = document.createElement('div'); box.className = 'window-controls';
    const fromLabel = document.createElement('label'); fromLabel.textContent = 'De la ';
    const from = document.createElement('input'); from.type = 'time'; from.value = stop.windowStart || ''; fromLabel.append(from);
    const toLabel = document.createElement('label'); toLabel.textContent = 'Până la ';
    const to = document.createElement('input'); to.type = 'time'; to.value = stop.windowEnd || ''; toLabel.append(to);
    box.append(fromLabel, toLabel);
    const saveWindow = () => { pushUndo(); stop.windowStart = from.value; stop.windowEnd = to.value; saveState(); setStatus('Fereastra orară a fost salvată'); };
    from.addEventListener('change', saveWindow); to.addEventListener('change', saveWindow); item.querySelector('div').append(box);
  });
}
function addGroupControls() { const list = $('#stops-list'); if (!list) return; list.querySelectorAll('.stop-item').forEach((item, index) => { const stop = state.stops[index]; if (!stop || item.querySelector('.group-control')) return; const input = document.createElement('input'); input.className = 'group-control'; input.type = 'text'; input.maxLength = 30; input.placeholder = 'Grup / zonă'; input.value = stop.group || ''; input.setAttribute('aria-label', `Grup stop ${index + 1}`); input.addEventListener('change', () => { pushUndo(); stop.group = input.value.trim(); saveState(); setStatus('Grupul stopului a fost salvat'); }); item.querySelector('div').append(input); }); }
const stopListObserver = new MutationObserver(() => addPriorityControls());
stopListObserver.observe($('#stops-list'), { childList: true });
const windowObserver = new MutationObserver(() => addWindowControls());
windowObserver.observe($('#stops-list'), { childList: true });
function addPackageControls() { const list = $('#stops-list'); if (!list) return; list.querySelectorAll('.stop-item').forEach((item, index) => { const stop = state.stops[index]; if (!stop || item.querySelector('.package-input')) return; const label = document.createElement('label'); label.className = 'package-control'; label.textContent = 'Colete '; const input = document.createElement('input'); input.className = 'package-input'; input.type = 'number'; input.min = '1'; input.max = '999'; input.step = '1'; input.inputMode = 'numeric'; input.value = String(Math.max(1, Number(stop.packageCount || 1))); input.setAttribute('aria-label', 'Număr colete stop ' + (index + 1)); input.addEventListener('change', () => { pushUndo(); stop.packageCount = Math.max(1, Math.min(999, Number(input.value) || 1)); input.value = String(stop.packageCount); invalidateOptimization(); saveState(); refreshList(); setStatus('Numărul de colete a fost salvat'); }); label.append(input); item.querySelector('div').append(label); }); }
const groupObserver = new MutationObserver(() => addGroupControls());
const packageObserver = new MutationObserver(() => addPackageControls());
packageObserver.observe($('#stops-list'), { childList: true });

groupObserver.observe($('#stops-list'), { childList: true });
function renderReview() {
  const list = $('#review-items'); if (!list) return; list.replaceChildren();
  const addRow = (label, point) => { if (!point) return; const item = document.createElement('li'); const strong = document.createElement('strong'); strong.textContent = label; const small = document.createElement('small'); small.textContent = (point.display_name || point.input || '') + (point.etaLabel ? ' · Sosire estimată ' + point.etaLabel : ''); item.append(strong, small); list.append(item); };
  addRow('Start', state.start);
  state.stops.forEach((stop, index) => addRow('Stop ' + (index + 1), stop));
  addRow('Finish', state.end || ($('#return-to-start').checked ? state.start : null));
}
function renderReviewMap() { if (!reviewMap) { reviewMap = L.map('review-map').setView([45.9432, 24.9668], 7); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; OpenStreetMap contributors' }).addTo(reviewMap); } reviewMarkers.forEach((marker) => marker.remove()); reviewMarkers = []; const pin = (color, label) => L.divIcon({ className: 'pin-icon', html: `<svg viewBox="0 0 38 48" aria-hidden="true"><path d="M19 1C9.1 1 1.5 8.4 1.5 17.5 1.5 29.5 19 47 19 47s17.5-17.5 17.5-29.5C36.5 8.4 28.9 1 19 1Z" fill="${color}" stroke="#f3fffb" stroke-width="2"/><text x="19" y="21" text-anchor="middle" fill="#fff" font-size="11" font-weight="800" font-family="Arial, sans-serif">${label}</text></svg>`, iconSize: [38, 48], iconAnchor: [19, 47] }); if (state.start) reviewMarkers.push(L.marker([state.start.lat, state.start.lon], { icon: pin('#e08a20', 'S') }).addTo(reviewMap)); state.stops.forEach((stop, index) => reviewMarkers.push(L.marker([stop.lat, stop.lon], { icon: pin('#0f8f7b', index + 1) }).addTo(reviewMap))); const end = state.end || ($('#return-to-start').checked ? state.start : null); if (end) reviewMarkers.push(L.marker([end.lat, end.lon], { icon: pin('#c84b63', 'F') }).addTo(reviewMap)); const points = [state.start, ...state.stops, end].filter(Boolean); if (points.length > 1) reviewMap.fitBounds(L.latLngBounds(points.map((point) => [point.lat, point.lon])).pad(.15)); setTimeout(() => reviewMap.invalidateSize(), 50); }
function renderFeasibilityReport() {
  const panel = $('#feasibility-report');
  if (!panel) return;
  const hasRoute = Boolean(state.routeDistance || state.stops.some((stop) => stop.etaAt) || state.end?.etaAt);
  if (!hasRoute) { panel.hidden = true; return; }
  const capacity = Math.max(1, Number($('#vehicle-capacity')?.value || 50));
  const packages = state.stops.reduce((sum, stop) => sum + Math.max(1, Number(stop.packageCount || 1)), 0);
  const lateStops = state.stops.filter((stop) => Number(stop.lateMinutes || 0) > 0);
  const waitingMinutes = state.stops.reduce((sum, stop) => sum + Number(stop.windowWaitMinutes || 0), 0);
  const issues = [];
  if (packages > capacity) issues.push(`Capacitate depășită: ${packages} colete din ${capacity}.`);
  lateStops.forEach((stop) => issues.push(`${stop.input || stop.display_name || 'Oprire'}: întârziere de ${stop.lateMinutes} min față de fereastra orară.`));
  if (waitingMinutes) issues.push(`Așteptare planificată la ferestrele de livrare: ${waitingMinutes} min.`);
  const feasible = packages <= capacity && lateStops.length === 0;
  const badge = $('#feasibility-badge');
  badge.textContent = feasible ? 'Realizabilă' : 'Necesită atenție';
  badge.className = 'feasibility-badge ' + (feasible ? 'feasibility-ok' : 'feasibility-warning');
  const finishText = state.end?.etaLabel ? ` Finish estimat: ${state.end.etaLabel}.` : '';
  $('#feasibility-summary').textContent = `${state.stops.length} opriri · ${packages} colete · ${lateStops.length} ferestre depășite.${finishText}`;
  const list = $('#feasibility-issues');
  list.replaceChildren();
  if (!issues.length) {
    const item = document.createElement('li'); item.textContent = 'Nu există conflicte detectate pentru capacitate sau ferestre orare.'; list.append(item);
  } else issues.slice(0, 8).forEach((message) => { const item = document.createElement('li'); item.textContent = message; list.append(item); });
  panel.hidden = false;
}
function renderRouteDetails() {
  const details = $('#route-details'); if (!details) return; details.replaceChildren();
  const addRow = (label, point, className = '', stopIndex = null) => {
    if (!point) return;
    const item = document.createElement('li'); item.className = className;
    const strong = document.createElement('strong'); strong.textContent = label;
    const address = document.createElement('span'); address.textContent = point.display_name || point.input || '';
    item.append(strong, address);
    if (point.etaLabel) { const eta = document.createElement('small'); eta.className = 'eta-label'; eta.textContent = 'Sosire estimată: ' + point.etaLabel; item.append(eta); }
    if (point.windowStart || point.windowEnd) { const window = document.createElement('small'); window.className = 'eta-label'; window.textContent = 'Fereastră: ' + (point.windowStart || '—') + '–' + (point.windowEnd || '—'); item.append(window); }
    if (state.editMode && stopIndex !== null) {
      const actions = document.createElement('div'); actions.className = 'order-actions';
      const labelNode = document.createElement('label'); labelNode.textContent = 'Poziția ';
      const input = document.createElement('input'); input.className = 'position-input'; input.type = 'number'; input.min = '1'; input.max = String(state.stops.length); input.value = String(stopIndex + 1); input.dataset.index = String(stopIndex); labelNode.append(input);
      const move = document.createElement('button'); move.type = 'button'; move.dataset.moveTo = ''; move.dataset.index = String(stopIndex); move.textContent = 'Mută'; labelNode.append(move); actions.append(labelNode);
      const addAction = (text, key, disabled = false) => { const button = document.createElement('button'); button.type = 'button'; button.dataset[key] = ''; button.dataset.index = String(stopIndex); button.textContent = text; button.disabled = disabled; actions.append(button); };
      addAction('↑', 'move', stopIndex === 0); actions.lastChild.dataset.move = 'up';
      addAction('↓', 'move', stopIndex === state.stops.length - 1); actions.lastChild.dataset.move = 'down';
      addAction('⇄ Schimbă', 'swap'); actions.append(); item.append(actions);
    }
    details.append(item);
  };
  addRow('Start', state.start, 'route-start'); state.stops.forEach((stop, index) => addRow('Stop ' + (index + 1), stop, '', index)); addRow('Finish', state.end || (state.start && $('#return-to-start').checked ? state.start : null), 'route-finish');
  details.querySelectorAll('[data-move]').forEach((button) => button.addEventListener('click', () => { const index = Number(button.dataset.index); const target = button.dataset.move === 'up' ? index - 1 : index + 1; if (target < 0 || target >= state.stops.length) return; pushUndo(); [state.stops[index], state.stops[target]] = [state.stops[target], state.stops[index]]; invalidateOptimization(); saveState(); drawMarkers(); refreshList(); renderRouteDetails(); setStatus('Ordinea a fost schimbată'); }));
  details.querySelectorAll('[data-move-to]').forEach((button) => button.addEventListener('click', () => { const index = Number(button.dataset.index); const input = details.querySelector('.position-input[data-index="' + index + '"]'); const target = Number(input.value) - 1; if (!Number.isInteger(target) || target < 0 || target >= state.stops.length) { setStatus('Poziția trebuie să fie între 1 și ' + state.stops.length + '.', true); return; } pushUndo(); const [stop] = state.stops.splice(index, 1); state.stops.splice(target, 0, stop); invalidateOptimization(); saveState(); drawMarkers(); refreshList(); renderRouteDetails(); setStatus('Stop mutat și renumerotat'); }));
  details.querySelectorAll('[data-swap]').forEach((button) => button.addEventListener('click', () => { const index = Number(button.dataset.index); if (state.swapSelection === undefined || state.swapSelection === null) { state.swapSelection = index; button.textContent = 'Alege al doilea'; setStatus('Stopul ' + (index + 1) + ' este selectat. Alege al doilea stop.'); return; } const other = state.swapSelection; state.swapSelection = null; if (other !== index) { pushUndo(); [state.stops[other], state.stops[index]] = [state.stops[index], state.stops[other]]; invalidateOptimization(); saveState(); drawMarkers(); refreshList(); renderRouteDetails(); setStatus('Cele două stopuri au fost schimbate'); } else { renderRouteDetails(); setStatus('Selectarea swap a fost anulată'); } }));
  $('#list-route-status').textContent = state.stops.length ? state.stops.length + ' opriri · ' + $('#route-distance').textContent + ' · ' + $('#route-duration').textContent : 'Adresele introduse';
}
function drawMarkers() {
  state.markers.forEach((marker) => marker.remove()); state.markers = [];
  if (state.routeLayer) { state.routeLayer.remove(); state.routeLayer = null; }
  const pinIcon = (color, label) => L.divIcon({ className: 'pin-icon', html: `<svg viewBox="0 0 38 48" aria-hidden="true"><path d="M19 1C9.1 1 1.5 8.4 1.5 17.5 1.5 29.5 19 47 19 47s17.5-17.5 17.5-29.5C36.5 8.4 28.9 1 19 1Z" fill="${color}" stroke="#f3fffb" stroke-width="2"/><circle cx="19" cy="17" r="10" fill="#ffffff33"/><text x="19" y="21" text-anchor="middle" fill="#fff" font-size="11" font-weight="800" font-family="Arial, sans-serif">${label}</text></svg>`, iconSize: [38, 48], iconAnchor: [19, 47] });
  const popupNode = (label, point) => { const box = document.createElement('div'); const title = document.createElement('strong'); title.textContent = label; const address = document.createElement('div'); address.textContent = point.display_name || point.input || ''; box.append(title, address); if (point.etaLabel) { const eta = document.createElement('small'); eta.textContent = `Sosire estimată: ${point.etaLabel}`; box.append(eta); } return box; };
  const startIcon = pinIcon('#e08a20', 'S');
  const stopIcon = (number) => pinIcon('#0f8f7b', number);
  const endIcon = pinIcon('#c84b63', 'F');
  if (state.start) { const marker = L.marker([state.start.lat, state.start.lon], { icon: startIcon, zIndexOffset: 1000 }).addTo(map); marker.bindPopup(popupNode('Start', state.start)); state.markers.push(marker); }
  state.stops.forEach((stop, index) => { const marker = L.marker([stop.lat, stop.lon], { icon: stopIcon(index + 1) }).addTo(map); marker.bindPopup(popupNode(`Oprirea ${index + 1}`, stop)); state.markers.push(marker); });
  if (state.end) { const marker = L.marker([state.end.lat, state.end.lon], { icon: endIcon, zIndexOffset: 900 }).addTo(map); marker.bindPopup(popupNode('Final', state.end)); state.markers.push(marker); }
  if (state.routeGeometry) state.routeLayer = L.geoJSON(state.routeGeometry, { style: { color: '#36b89b', weight: 5, opacity: .8 } }).addTo(map);
  const all = [state.start, ...state.stops, state.end].filter(Boolean); if (all.length > 1) map.fitBounds(L.latLngBounds(all.map((point) => [point.lat, point.lon])).pad(.15));
}
function geocodePayload(result, input) { return { lat: Number(result.lat), lon: Number(result.lon), display_name: result.display_name, input, address: result.address || {}, postalCode: result.address?.postcode || '', city: result.address?.city || result.address?.town || result.address?.village || result.address?.municipality || '', countryCode: result.address?.country_code || '' }; }
function chooseGeocodeResult(results, address) { if (results.length === 1) return Promise.resolve(geocodePayload(results[0], address)); return new Promise((resolve) => { const modal = $('#address-results-modal'); const list = $('#address-results'); list.replaceChildren(); results.forEach((result) => { const button = document.createElement('button'); button.type = 'button'; button.className = 'address-result-option'; const title = document.createElement('strong'); title.textContent = result.display_name || 'Adresă găsită'; const details = document.createElement('small'); const city = result.address?.city || result.address?.town || result.address?.village || result.address?.municipality || ''; const postcode = result.address?.postcode || ''; details.textContent = `${city ? `${city} · ` : ''}${postcode ? `Cod poștal ${postcode} · ` : ''}${result.type || 'Adresă găsită'} · ${result.lat}, ${result.lon}`; button.append(title, details); button.addEventListener('click', () => { modal.hidden = true; resolve(geocodePayload(result, address)); }); list.append(button); }); $('#cancel-address-results').onclick = () => { modal.hidden = true; resolve(null); }; modal.hidden = false; }); }let geocodeNextAllowedAt = 0; async function waitForGeocoder() { const delay = Math.max(0, geocodeNextAllowedAt - Date.now()); if (delay) await new Promise((resolve) => setTimeout(resolve, delay)); geocodeNextAllowedAt = Date.now() + 1050; }
async function geocode(address) { const normalized = address.trim().toLowerCase(); let cache = {}; try { cache = JSON.parse(localStorage.getItem(GEOCODE_CACHE_KEY) || '{}'); } catch { cache = {}; } if (cache[normalized]) return { ...cache[normalized], input: address }; if (navigator.onLine === false) throw new Error('Ești offline. Folosește o adresă memorată sau reconectează-te pentru o adresă nouă.'); await waitForGeocoder(); const url = `https://nominatim.openstreetmap.org/search?format=jsonv2&addressdetails=1&dedupe=1&limit=5&countrycodes=ro&accept-language=ro&q=${encodeURIComponent(`${address}, România`)}`; const controller = new AbortController(); const timeout = window.setTimeout(() => controller.abort(), 12000); let response; try { response = await fetch(url, { headers: { Accept: 'application/json' }, signal: controller.signal }); } catch (error) { if (error.name === 'AbortError') throw new Error('Căutarea a durat prea mult. Verifică internetul și încearcă din nou.'); throw new Error('Serviciul de căutare nu răspunde momentan.'); } finally { window.clearTimeout(timeout); } if (response.status === 429) throw new Error('Căutarea este temporar limitată. Alege o adresă din sugestiile memorate sau încearcă din nou peste câteva secunde.'); if (!response.ok) throw new Error('Serviciul de căutare nu răspunde momentan.'); const results = await response.json(); if (!results.length) throw new Error(`Nu am găsit adresa „${address}”.`); const location = await chooseGeocodeResult(results, address); if (!location) return null; if (location.countryCode && location.countryCode !== 'ro') throw new Error('Alege o adresă din România.'); cache[normalized] = location; const entries = Object.entries(cache); if (entries.length > 200) cache = Object.fromEntries(entries.slice(-200)); try { localStorage.setItem(GEOCODE_CACHE_KEY, JSON.stringify(cache)); } catch { /* căutarea rămâne validă chiar fără cache */ } return location; }function refreshAddressSuggestions() { const datalist = $('#address-suggestions'); if (!datalist) return; let history = []; try { history = JSON.parse(localStorage.getItem(ADDRESS_HISTORY_KEY) || '[]'); } catch { history = []; } datalist.innerHTML = ''; history.slice(0, 20).forEach((address) => { const option = document.createElement('option'); option.value = address; datalist.append(option); }); }
function rememberAddress(address) { if (!address) return; let history = []; try { history = JSON.parse(localStorage.getItem(ADDRESS_HISTORY_KEY) || '[]'); } catch { history = []; } history = [address, ...history.filter((item) => item.toLowerCase() !== address.toLowerCase())].slice(0, 50); try { localStorage.setItem(ADDRESS_HISTORY_KEY, JSON.stringify(history)); } catch {} refreshAddressSuggestions(); }async function addAddress(kind) { const input = kind === 'start' ? $('#start-address') : kind === 'end' ? $('#end-address') : $('#stop-address'); const address = input.value.trim(); if (!address) return; setStatus('Caut adresa…'); input.disabled = true; const editIndex = editingStopIndex; try { const location = await geocode(address); if (!location) { setStatus('Alege o adresă din rezultate.'); return; } location.input = address; rememberAddress(address); pushUndo(); invalidateOptimization(); if (kind === 'start') state.start = location; else if (kind === 'end') state.end = location; else { const duplicate = state.stops.some((stop, index) => index !== editIndex && Math.abs(stop.lat - location.lat) < 0.0001 && Math.abs(stop.lon - location.lon) < 0.0001); if (duplicate) throw new Error('Această oprire există deja în rută.'); const previous = editIndex !== null && editIndex >= 0 && editIndex < state.stops.length ? state.stops[editIndex] : null; const serviceValue = $('#service-time').value; const updated = { ...(previous || {}), ...location, serviceTime: serviceValue === '' ? Number(previous?.serviceTime || 0) : Math.max(0, Number(serviceValue) || 0), packageCount: Math.max(1, Number(previous?.packageCount || 1)) }; if (editIndex !== null && editIndex >= 0 && editIndex < state.stops.length) { state.stops[editIndex] = updated; editingStopIndex = null; } else { state.stops.push(updated); } input.value = ''; } saveState(); drawMarkers(); refreshList(); setStatus(kind === 'start' ? 'Start setat și salvat' : kind === 'end' ? 'Finish setat și salvat' : editIndex !== null ? 'Adresa stopului a fost actualizată' : 'Oprire adăugată'); } catch (error) { setStatus(error.message, true); } finally { input.disabled = false; input.focus(); } }function useCurrentLocation(kind = 'start') {
  if (!navigator.geolocation) { setStatus('Browserul nu oferă locația GPS.', true); return; } setStatus('Obțin locația exactă…');
  navigator.geolocation.getCurrentPosition(({ coords }) => { const location = { lat: coords.latitude, lon: coords.longitude, display_name: 'Locația GPS curentă a curierului', input: 'Locația GPS curentă' }; pushUndo(); invalidateOptimization(); if (kind === 'end') { state.end = location; $('#end-address').value = location.display_name; } else { state.start = location; $('#start-address').value = location.display_name; } saveState(); drawMarkers(); refreshList(); setStatus(kind === 'end' ? 'Finish GPS setat și ruta veche invalidată' : 'Start GPS setat și ruta veche invalidată'); }, () => setStatus('Nu am putut obține locația. Verifică permisiunea GPS.', true), { enableHighAccuracy: true, timeout: 10000 });
}
function approximateDistanceMeters(a, b) { const lat1 = Number(a.lat) * Math.PI / 180; const lat2 = Number(b.lat) * Math.PI / 180; const dLat = (Number(b.lat) - Number(a.lat)) * Math.PI / 180; const dLon = (Number(b.lon) - Number(a.lon)) * Math.PI / 180; const h = Math.sin(dLat / 2) ** 2 + Math.cos(lat1) * Math.cos(lat2) * Math.sin(dLon / 2) ** 2; return 6371000 * 2 * Math.atan2(Math.sqrt(h), Math.sqrt(1 - h)); }
function approximateDistanceMatrix(points) { return points.map((from) => points.map((to) => approximateDistanceMeters(from, to))); }
function approximateDurationMatrix(points) { const averageSpeed = 35 * 1000 / 3600; return points.map((from) => points.map((to) => approximateDistanceMeters(from, to) / averageSpeed)); }
function approximateRoute(points) { const coordinates = points.map((point) => [Number(point.lon), Number(point.lat)]); return { geometry: { type: 'LineString', coordinates }, distance: coordinates.slice(1).reduce((total, current, index) => total + approximateDistanceMeters(points[index], points[index + 1]), 0), duration: coordinates.slice(1).reduce((total, current, index) => total + approximateDistanceMeters(points[index], points[index + 1]) / (35 * 1000 / 3600), 0) }; }
function routeCost(order, matrix, closeLoop) { let cost = 0; for (let i = 0; i < order.length - 1; i += 1) cost += matrix[order[i]][order[i + 1]] || Infinity; if (closeLoop && order.length > 1) cost += matrix[order[order.length - 1]][order[0]] || Infinity; return cost; }
function exactOrder(order, matrix, closeLoop, fixedEnd) {
  const endIndex = fixedEnd ? order[order.length - 1] : null;
  const nodes = order.filter((index) => index !== 0 && index !== endIndex);
  if (nodes.length > 9) return null;
  if (!nodes.length) return fixedEnd ? [0, endIndex] : [0];
  const states = new Map();
  nodes.forEach((node, index) => states.set((1 << index) + ':' + index, { cost: Number(matrix[0][node] || Infinity), path: [node] }));
  for (let mask = 1; mask < (1 << nodes.length); mask += 1) {
    for (let last = 0; last < nodes.length; last += 1) {
      if (!(mask & (1 << last))) continue;
      const current = states.get(mask + ':' + last); if (!current) continue;
      for (let next = 0; next < nodes.length; next += 1) {
        if (mask & (1 << next)) continue;
        const candidate = { cost: current.cost + Number(matrix[nodes[last]][nodes[next]] || Infinity), path: [...current.path, nodes[next]] };
        const key = (mask | (1 << next)) + ':' + next; const previous = states.get(key);
        if (!previous || candidate.cost < previous.cost) states.set(key, candidate);
      }
    }
  }
  const fullMask = (1 << nodes.length) - 1; let best = null;
  for (let last = 0; last < nodes.length; last += 1) {
    const current = states.get(fullMask + ':' + last); if (!current) continue;
    const returnCost = fixedEnd ? Number(matrix[nodes[last]][endIndex] || Infinity) : closeLoop ? Number(matrix[nodes[last]][0] || Infinity) : 0;
    const candidate = { cost: current.cost + returnCost, path: current.path };
    if (!best || candidate.cost < best.cost) best = candidate;
  }
  return best ? [0, ...best.path, ...(fixedEnd ? [endIndex] : [])] : null;
}
function improveOrder(order, matrix, closeLoop, fixedEnd) {
  let improved = true; let currentCost = routeCost(order, matrix, closeLoop); let passes = 0;
  while (improved && passes < 40) { improved = false; passes += 1; const lastReversible = fixedEnd ? order.length - 2 : order.length - 1;
    for (let i = 1; i < lastReversible; i += 1) for (let k = i + 1; k <= lastReversible; k += 1) { const candidate = order.slice(0, i).concat(order.slice(i, k + 1).reverse(), order.slice(k + 1)); const candidateCost = routeCost(candidate, matrix, closeLoop); if (candidateCost + 1 < currentCost) { order = candidate; currentCost = candidateCost; improved = true; } }
  }
  return order;
}
function validateRoute() { if (!state.start) return 'Setează punctul de plecare.'; if (!state.stops.length) return 'Adaugă cel puțin o oprire.'; const vehicleCapacity = Math.max(1, Number($('#vehicle-capacity')?.value || 50)); const totalPackages = state.stops.reduce((sum, stop) => sum + Math.max(1, Number(stop.packageCount || 1)), 0); if (totalPackages > vehicleCapacity) return 'Capacitatea vehiculului este depășită: ' + totalPackages + ' colete din ' + vehicleCapacity + '.'; const startKey = `${Number(state.start.lat).toFixed(5)},${Number(state.start.lon).toFixed(5)}`; const seen = new Set([startKey]); for (const [index, stop] of state.stops.entries()) { const key = `${Number(stop.lat).toFixed(5)},${Number(stop.lon).toFixed(5)}`; if (seen.has(key)) return `Stopul ${index + 1} este duplicat sau coincide cu Start.`; seen.add(key); if (stop.windowStart && stop.windowEnd && stop.windowEnd < stop.windowStart) return `Fereastra orară a stopului ${index + 1} este invalidă.`; } if (state.end) { const endKey = `${Number(state.end.lat).toFixed(5)},${Number(state.end.lon).toFixed(5)}`; if (endKey === startKey && !$('#return-to-start').checked) return 'Finish-ul coincide cu Start-ul. Activează întoarcerea la plecare sau alege alt Finish.'; if (seen.has(endKey) && endKey !== startKey) return 'Finish-ul coincide cu una dintre opriri.'; } return ''; }
function getTrafficFactor(level, timestamp = Date.now()) { if (level === 'busy') return 1.18; if (level === 'heavy') return 1.35; if (level !== 'auto') return 1; const date = new Date(timestamp); const hour = date.getHours() + date.getMinutes() / 60; return (hour >= 7 && hour < 10) || (hour >= 16 && hour < 19) ? 1.24 : 1.05; }
function candidateScore(from, to, matrix, points, priorityWeight, elapsedMinutes = 0, startTimestamp = Date.now(), durationMatrix = matrix) { const stop = points[to]; const travelMinutes = Number(durationMatrix[from][to] || 0) / 60; let score = (matrix[from][to] ?? Infinity) - (stop.priority || 1) * priorityWeight - (points[from].group && points[from].group === stop.group ? 300 : 0); const arrival = new Date(startTimestamp + (elapsedMinutes + travelMinutes) * 60000); if (stop.windowStart || stop.windowEnd) { const opening = stop.windowStart ? new Date(arrival) : null; const closing = stop.windowEnd ? new Date(arrival) : null; if (opening) { const [hours, minutes] = stop.windowStart.split(':').map(Number); opening.setHours(hours, minutes, 0, 0); if (opening > arrival) score += (opening - arrival) / 60000 * 2; } if (closing) { const [hours, minutes] = stop.windowEnd.split(':').map(Number); closing.setHours(hours, minutes, 0, 0); if (arrival > closing) score += 100000 + Math.round((arrival - closing) / 60000) * 100; } } return score; }async function calculateRoute() {
  const validationError = validateRoute(); if (validationError) { setStatus(validationError, true); return; } setStatus('Calculez timpii și optimizez traseul…');
  const points = [state.start, ...state.stops, ...(state.end ? [state.end] : [])]; const fixedEnd = Boolean(state.end); const closeLoop = !fixedEnd && $('#return-to-start').checked;
  let usingLocalEstimate = false;
  try {
    const coordinates = points.map((point) => `${point.lon},${point.lat}`).join(';'); const avoidance = $('#road-avoidance')?.value || 'none'; const routingOptions = avoidance === 'none' ? '' : `&exclude=${encodeURIComponent(avoidance)}`; let matrix; let distanceMatrix; try { const tableResponse = await fetchRoutingWithRetry(`https://router.project-osrm.org/table/v1/driving/${coordinates}?annotations=duration,distance${routingOptions}`); const table = await tableResponse.json(); if (!table.durations) throw new Error('Nu am putut calcula timpii dintre opriri.'); matrix = table.durations; distanceMatrix = table.distances || approximateDistanceMatrix(points); } catch { usingLocalEstimate = true; matrix = approximateDurationMatrix(points); distanceMatrix = approximateDistanceMatrix(points); }
    const endIndex = fixedEnd ? points.length - 1 : null; const remaining = []; for (let index = 1; index < points.length; index += 1) if (index !== endIndex) remaining.push(index);
    const blockedStops = state.stops.filter((point) => blockedRoadMatch(point)); if (!state.routeId) state.routeId = `route-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`; const optimizationMode = $('#optimization-mode')?.value || 'balanced'; const priorityWeight = optimizationMode === 'priority' ? 120 : optimizationMode === 'fastest' ? 30 : optimizationMode === 'shortest' ? 0 : 60; const optimizationMatrix = optimizationMode === 'shortest' ? distanceMatrix : matrix; const departureValue = $('#departure-time')?.value; const breakAfter = Math.max(0, Number($('#break-after')?.value || 0)); const breakDuration = Math.max(0, Number($('#break-duration')?.value || 0)); const now = new Date(); const planningStart = departureValue ? (() => { const [hours, minutes] = departureValue.split(':').map(Number); const departure = new Date(now); departure.setHours(hours, minutes, 0, 0); return departure.getTime(); })() : Date.now(); const order = [0]; let current = 0; let elapsedMinutes = 0; while (remaining.length) { let bestAt = 0; for (let index = 1; index < remaining.length; index += 1) if (candidateScore(current, remaining[index], optimizationMatrix, points, priorityWeight, elapsedMinutes, planningStart, matrix) < candidateScore(current, remaining[bestAt], optimizationMatrix, points, priorityWeight, elapsedMinutes, planningStart, matrix)) bestAt = index; const next = remaining.splice(bestAt, 1)[0]; const travelMinutes = Number(matrix[current][next] || 0) / 60; elapsedMinutes += travelMinutes; const selected = points[next]; if (selected.windowStart) { const [hours, minutes] = selected.windowStart.split(':').map(Number); const opening = new Date(planningStart + elapsedMinutes * 60000); opening.setHours(hours, minutes, 0, 0); if (opening.getTime() > planningStart + elapsedMinutes * 60000) elapsedMinutes += (opening.getTime() - (planningStart + elapsedMinutes * 60000)) / 60000; } elapsedMinutes += Number(selected.serviceTime || 0); if (breakAfter > 0 && order.length % breakAfter === 0 && remaining.length) elapsedMinutes += breakDuration; current = next; order.push(current); }
    if (fixedEnd) order.push(endIndex); const hasConstraints = state.stops.some((point) => point.locked || point.windowStart || point.windowEnd); const exact = optimizationMode !== 'priority' && !hasConstraints ? exactOrder(order, optimizationMatrix, closeLoop, fixedEnd) : null; const optimizedOrderRaw = exact || improveOrder(order, optimizationMatrix, closeLoop, fixedEnd); const lockedSlots = new Map(); points.forEach((point, index) => { if (point.locked) lockedSlots.set(index, index); }); const optimizedOrder = lockedSlots.size ? (() => { const result = Array(optimizedOrderRaw.length).fill(null); lockedSlots.forEach((slot, pointIndex) => { if (slot < result.length && slot !== 0 && !(fixedEnd && slot === endIndex)) result[slot] = pointIndex; }); const free = optimizedOrderRaw.filter((pointIndex) => !lockedSlots.has(pointIndex) && pointIndex !== endIndex); let cursor = 1; free.forEach((pointIndex) => { while (cursor < result.length && result[cursor] !== null) cursor += 1; if (cursor < result.length - (fixedEnd ? 1 : 0)) result[cursor] = pointIndex; }); if (fixedEnd) result[result.length - 1] = endIndex; return result.filter((pointIndex) => pointIndex !== null); })() : optimizedOrderRaw; const routePoints = optimizedOrder.map((index) => points[index]); if (closeLoop) routePoints.push(points[0]);
    const routeCoordinates = routePoints.map((point) => `${point.lon},${point.lat}`).join(';'); let route; try { const routeResponse = await fetchRoutingWithRetry(`https://router.project-osrm.org/route/v1/driving/${routeCoordinates}?overview=full&geometries=geojson&steps=false${routingOptions}`); const routeData = await routeResponse.json(); if (!routeData.routes?.length) throw new Error('Nu am putut desena ruta optimizată.'); route = routeData.routes[0]; } catch { usingLocalEstimate = true; route = approximateRoute(routePoints); } state.routeGeometry = route.geometry;
    const optimizationStartedAt = departureValue ? (() => { const [hours, minutes] = departureValue.split(':').map(Number); const departure = new Date(now); departure.setHours(hours, minutes, 0, 0); return departure.getTime(); })() : Date.now(); const vehicleProfile = $('#vehicle-profile')?.value || 'car'; const vehicleFactor = vehicleProfile === 'van' ? 1.12 : vehicleProfile === 'bike' ? 0.82 : 1; const trafficLevel = document.querySelector('#traffic-level')?.value || 'auto'; const trafficFactor = getTrafficFactor(trafficLevel, planningStart); let etaElapsedMinutes = 0; const etaByPoint = new Map([[0, optimizationStartedAt]]); for (let i = 1; i < optimizedOrder.length; i += 1) { const previous = optimizedOrder[i - 1]; const currentPoint = optimizedOrder[i]; etaElapsedMinutes += Number(matrix[previous][currentPoint] || 0) / 60 * vehicleFactor * trafficFactor; etaByPoint.set(currentPoint, optimizationStartedAt + etaElapsedMinutes * 60000); if (currentPoint !== endIndex) etaElapsedMinutes += Number(points[currentPoint].serviceTime || 0); if (breakAfter > 0 && i < optimizedOrder.length - 1 && (i % breakAfter) === 0) etaElapsedMinutes += breakDuration; } state.stops = optimizedOrder.slice(1, fixedEnd ? -1 : undefined).map((index) => ({ ...points[index], etaAt: etaByPoint.get(index), etaLabel: formatClock(etaByPoint.get(index)) })); if (fixedEnd && state.end && etaByPoint.has(endIndex)) state.end = { ...state.end, etaAt: etaByPoint.get(endIndex), etaLabel: formatClock(etaByPoint.get(endIndex)) }; if (state.routeLayer) state.routeLayer.remove(); const routeStyle = usingLocalEstimate ? { color: '#d08a28', weight: 5, opacity: .85, dashArray: '8 8' } : { color: '#0f766e', weight: 5, opacity: .85 }; state.routeLayer = L.geoJSON(route.geometry, { style: routeStyle }).addTo(map);
    let windowDelay = 0; state.stops.forEach((stop) => { const baseEta = Number(stop.etaAt || 0); const eta = new Date(baseEta + windowDelay * 60000); if (stop.windowStart) { const [hours, minutes] = stop.windowStart.split(':').map(Number); const opening = new Date(eta); opening.setHours(hours, minutes, 0, 0); if (opening > eta) { const waitMinutes = (opening - eta) / 60000; windowDelay += waitMinutes; stop.windowWaitMinutes = Math.round(waitMinutes); } } stop.etaAt = baseEta + windowDelay * 60000; stop.etaLabel = formatClock(stop.etaAt); if (stop.windowEnd) { const [hours, minutes] = stop.windowEnd.split(':').map(Number); const closing = new Date(stop.etaAt); closing.setHours(hours, minutes, 0, 0); stop.lateMinutes = Math.max(0, Math.round((stop.etaAt - closing) / 60000)); } }); if (fixedEnd && state.end?.etaAt && windowDelay) { state.end.etaAt += windowDelay * 60000; state.end.etaLabel = formatClock(state.end.etaAt); }
    const serviceMinutes = state.stops.reduce((sum, stop) => sum + (stop.serviceTime || 0), 0); const plannedBreakMinutes = breakAfter > 0 ? Math.floor(Math.max(0, state.stops.length - 1) / breakAfter) * breakDuration : 0; state.routeDistance = route.distance; state.routeDuration = (Math.round(route.duration / 60 * vehicleFactor * trafficFactor) + serviceMinutes + Math.round(windowDelay) + plannedBreakMinutes) * 60; $('#route-distance').textContent = `${(route.distance / 1000).toFixed(1)} km`; $('#route-duration').textContent = formatDuration(Math.round(state.routeDuration / 60)); saveState(); $('#finish-route').hidden = false; drawMarkers(); refreshList(); map.fitBounds(state.routeLayer.getBounds().pad(.12)); const lateWindowCount = state.stops.filter((stop) => Number(stop.lateMinutes || 0) > 0).length; const routeMessage = usingLocalEstimate ? 'Rută optimizată local — estimare fără OSRM' : 'Rută optimizată'; const blockedMessage = blockedStops.length ? ` · ${blockedStops.length} stopuri pe drumuri de verificat` : ''; setStatus(lateWindowCount ? `${routeMessage}${blockedMessage} · ${lateWindowCount} ferestre depășite` : `${routeMessage}${blockedMessage}`);
  } catch (error) { const fallbackPoints = [state.start, ...state.stops, ...(state.end ? [state.end] : [])].filter(Boolean); if (fallbackPoints.length > 1) { if (state.routeLayer) state.routeLayer.remove(); state.routeLayer = L.polyline(fallbackPoints.map((point) => [point.lat, point.lon]), { color: '#d08a28', weight: 4, dashArray: '8 8', opacity: .85 }).addTo(map); drawMarkers(); refreshList(); map.fitBounds(state.routeLayer.getBounds().pad(.1)); $('#finish-route').hidden = false; setStatus('Rută locală aproximativă — serviciul de rutare nu răspunde', false); } else setStatus(error.message, true); }
}
function openNavigation(index) { const stop = state.stops[index]; if (stop) window.open(`https://www.google.com/maps/dir/?api=1&destination=${stop.lat},${stop.lon}`, '_blank', 'noopener'); }
function exportCsv() { const rows = [['tip', 'ordine', 'adresa', 'ora_sosire', 'status', 'notita', 'cod_postal', 'latitudine', 'longitudine', 'minute_stationare_planificate', 'minute_stationare_reale', 'colete', 'livrat']]; const addRow = (type, order, point, status = '', note = '', serviceTime = '', delivered = '') => { if (!point) return; rows.push([type, order, point.input || point.display_name || '', point.etaLabel || '', status || point.statusLabel || '', note || point.note || '', point.postalCode || point.address?.postcode || '', point.lat ?? '', point.lon ?? '', serviceTime || point.serviceTime || '', point.actualServiceMinutes || '', point.packageCount || '', delivered]); }; addRow('Start', '', state.start); state.stops.forEach((stop, index) => addRow('Stop', index + 1, stop, stop.statusLabel || (stop.delivered ? 'Livrat' : 'Neprocesat'), stop.note || '', stop.serviceTime || 0, stop.delivered ? 'da' : 'nu')); addRow('Finish', '', state.end); const csv = rows.map((row) => row.map((value) => `"${String(value).replaceAll('\"', '\"\"')}"`).join(';')).join('\n'); const blob = new Blob([`\ufeff${csv}`], { type: 'text/csv;charset=utf-8' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `ruta-${new Date().toISOString().slice(0, 10)}.csv`; link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 500); setStatus('CSV exportat cu Start, Finish, ETA, colete și statusuri'); }
function downloadFile(name, content, type) { const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([content], { type })); link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 500); }
function exportBackup() { downloadFile(`route-optimizer-backup-${new Date().toISOString().slice(0, 10)}.json`, JSON.stringify({ version: 5, routeId: state.routeId || '', savedAt: new Date().toISOString(), start: state.start, end: state.end, stops: state.stops, routeGeometry: state.routeGeometry, routeDistance: state.routeDistance || 0, routeDuration: state.routeDuration || 0, returnToStart: $('#return-to-start').checked, serviceTime: $('#service-time').value, breakAfter: $('#break-after')?.value || '0', breakDuration: $('#break-duration')?.value || '15', departureTime: $('#departure-time').value, optimizationMode: $('#optimization-mode')?.value || 'balanced', vehicleProfile: $('#vehicle-profile')?.value || 'car', trafficLevel: $('#traffic-level')?.value || 'normal', vehicleCapacity: Math.max(1, Number($('#vehicle-capacity')?.value || 50)), roadAvoidance: $('#road-avoidance')?.value || 'none', blockedRoads: $('#blocked-roads')?.value || '' }, null, 2), 'application/json'); setStatus('Backup salvat'); }
function applyImportedBackup(data) { if (!data || !Array.isArray(data.stops)) throw new Error('Fișierul nu este un backup valid.'); if (state.routeLayer) { state.routeLayer.remove(); state.routeLayer = null; } state.routeId = String(data.routeId || state.routeId || ''); state.start = cleanPoint(data.start); state.end = cleanPoint(data.end); state.stops = cleanStops(data.stops); state.routeGeometry = data.routeGeometry || null; state.routeDistance = Number(data.routeDistance || 0); state.routeDuration = Number(data.routeDuration || 0); $('#return-to-start').checked = Boolean(data.returnToStart); if (data.serviceTime !== undefined) $('#service-time').value = data.serviceTime; if (data.breakAfter !== undefined && $('#break-after')) $('#break-after').value = data.breakAfter; if (data.breakDuration !== undefined && $('#break-duration')) $('#break-duration').value = data.breakDuration; if (data.departureTime) $('#departure-time').value = data.departureTime; if (data.optimizationMode && $('#optimization-mode')) $('#optimization-mode').value = data.optimizationMode; if (data.vehicleProfile && $('#vehicle-profile')) $('#vehicle-profile').value = data.vehicleProfile; if (data.trafficLevel && $('#traffic-level')) $('#traffic-level').value = data.trafficLevel; if (data.vehicleCapacity !== undefined && $('#vehicle-capacity')) $('#vehicle-capacity').value = data.vehicleCapacity; if (data.roadAvoidance && $('#road-avoidance')) $('#road-avoidance').value = data.roadAvoidance; if (data.blockedRoads !== undefined && $('#blocked-roads')) $('#blocked-roads').value = data.blockedRoads; $('#start-address').value = state.start?.input || state.start?.display_name || ''; $('#end-address').value = state.end?.input || state.end?.display_name || ''; saveState(); drawMarkers(); refreshList(); setStatus('Backup încărcat'); }
$('#set-start').addEventListener('click', () => addAddress('start')); $('#set-end').addEventListener('click', () => addAddress('end')); $('#add-stop').addEventListener('click', () => addAddress('stop')); $('#current-start-location').addEventListener('click', () => useCurrentLocation('start')); $('#current-end-location').addEventListener('click', () => useCurrentLocation('end')); $('#start-address').addEventListener('keydown', (event) => { if (event.key === 'Enter') addAddress('start'); }); $('#end-address').addEventListener('keydown', (event) => { if (event.key === 'Enter') addAddress('end'); }); $('#stop-address').addEventListener('keydown', (event) => { if (event.key === 'Enter') addAddress('stop'); }); $('#optimize').addEventListener('click', calculateRoute);
function parseCsvRows(text) { const rows = []; let row = []; let field = ''; let quoted = false; for (let index = 0; index < text.length; index += 1) { const char = text[index]; if (char === '"' && text[index + 1] === '"' && quoted) { field += '"'; index += 1; } else if (char === '"') quoted = !quoted; else if ((char === ';' || char === ',') && !quoted) { row.push(field.trim()); field = ''; } else if ((char === '\n' || char === '\r') && !quoted) { if (char === '\r' && text[index + 1] === '\n') index += 1; row.push(field.trim()); if (row.some(Boolean)) rows.push(row); row = []; field = ''; } else field += char; } if (field.trim() || row.length) { row.push(field.trim()); rows.push(row); } return rows; }
$('#csv-file').addEventListener('change', async (event) => { const file = event.target.files[0]; if (!file) return; const rows = parseCsvRows(await file.text()); const addresses = rows.filter((row) => row[0] && !/^(adresă|adresa|address|stradă|street)$/i.test(row[0].trim())).map((row) => row[0]); setStatus(`Import ${addresses.length} adrese…`); let added = 0; let skipped = 0; for (const address of addresses) { try { const location = await geocode(address); const duplicate = state.stops.some((stop) => Math.abs(stop.lat - location.lat) < 0.0001 && Math.abs(stop.lon - location.lon) < 0.0001); if (duplicate) { skipped += 1; continue; } state.stops.push({ ...location, input: address, serviceTime: Number($('#service-time').value) || 0 }); added += 1; } catch { skipped += 1; } } saveState(); drawMarkers(); refreshList(); setStatus(`Import CSV finalizat: ${added} adăugate, ${skipped} ignorate`); event.target.value = ''; });
$('#clear-all').addEventListener('click', () => { if (!window.confirm('Ștergi Start-ul, Finish-ul și toate opririle din ruta activă?')) return; pushUndo(); state.routeId = ''; state.start = null; state.end = null; state.stops = []; localStorage.removeItem(STORAGE_KEY); $('#start-address').value = ''; $('#end-address').value = ''; state.markers.forEach((marker) => marker.remove()); state.markers = []; if (state.routeLayer) state.routeLayer.remove(); state.routeLayer = null; $('#route-distance').textContent = '—'; $('#route-duration').textContent = '—'; saveState(); refreshList(); setStatus('Pregătit'); });
$('#export-csv').addEventListener('click', exportCsv); $('#undo-change').addEventListener('click', undoLastChange); $('#redo-change').addEventListener('click', redoLastChange);
$('#toggle-edit-order').addEventListener('click', () => { state.editMode = !state.editMode; $('#toggle-edit-order').textContent = state.editMode ? 'Gata cu editarea' : 'Editează ordinea'; renderRouteDetails(); });
$('#export-backup')?.addEventListener('click', exportBackup); $('#import-backup-button')?.addEventListener('click', () => $('#import-backup').click()); $('#import-backup')?.addEventListener('change', async (event) => { const file = event.target.files[0]; if (!file) return; try { applyImportedBackup(JSON.parse(await file.text())); } catch (error) { setStatus(error.message || 'Backup invalid.', true); } event.target.value = ''; });
$('#review-route').addEventListener('click', () => { renderReview(); $('#review-modal').hidden = false; }); $('#back-to-entry').addEventListener('click', () => { $('#review-modal').hidden = true; }); $('#toggle-review-map').addEventListener('click', () => { const showingMap = !$('#review-map').hidden; $('#review-map').hidden = showingMap; $('#review-items').hidden = !showingMap; $('#toggle-review-map').textContent = showingMap ? 'Vezi harta' : 'Vezi adresele'; if (!showingMap) renderReviewMap(); }); $('#optimize-from-review').addEventListener('click', async () => { await calculateRoute(); if (!$('#finish-route').hidden) $('#review-modal').hidden = true; });
$('#bulk-add').addEventListener('click', () => { $('#bulk-modal').hidden = false; $('#bulk-addresses').focus(); }); $('#close-bulk').addEventListener('click', () => { $('#bulk-modal').hidden = true; }); $('#bulk-done').addEventListener('click', addBulkAddresses); $('#bulk-voice').addEventListener('click', startBulkVoice); $('#bulk-camera').addEventListener('click', () => $('#bulk-image').click()); $('#bulk-image').addEventListener('change', (event) => { scanBulkImage(event.target.files[0]); event.target.value = ''; });
function stopActiveRecognition() { if (activeRecognition) { activeRecognition.stop(); activeRecognition = null; } if (activeMicButton) { activeMicButton.classList.remove('listening'); activeMicButton = null; } }
function startVoiceInput(inputId, button) { const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition; if (!SpeechRecognition) { setStatus('Browserul nu suportă dictarea vocală.', true); return; } if (activeRecognition && activeMicButton === button) { stopActiveRecognition(); setStatus('Microfon oprit'); return; } stopActiveRecognition(); const input = document.getElementById(inputId); const recognition = new SpeechRecognition(); activeRecognition = recognition; activeMicButton = button; recognition.lang = 'ro-RO'; recognition.interimResults = false; recognition.maxAlternatives = 1; button.classList.add('listening'); setStatus('Ascult… apasă din nou pentru oprire'); recognition.onresult = (event) => { input.value = event.results[0][0].transcript; input.focus(); }; recognition.onerror = () => setStatus('Nu am putut înțelege adresa. Încearcă din nou.', true); recognition.onend = () => { if (activeRecognition === recognition) stopActiveRecognition(); }; recognition.start(); }document.querySelectorAll('.mic-button').forEach((button) => button.addEventListener('click', () => startVoiceInput(button.dataset.input, button)));
async function addBulkAddresses() { const lines = $('#bulk-addresses').value.split(/\r?\n/).map((line) => line.trim()).filter(Boolean); if (!lines.length) { setStatus('Adaugă cel puțin o adresă.', true); return; } setStatus(`Caut ${lines.length} adrese…`); let added = 0; for (const address of lines) { try { const location = await geocode(address); const duplicate = state.stops.some((stop) => Math.abs(stop.lat - location.lat) < 0.0001 && Math.abs(stop.lon - location.lon) < 0.0001); if (!duplicate) { state.stops.push({ ...location, input: address, serviceTime: Number($('#service-time').value) || 0 }); added += 1; } } catch { /* adresa rămâne în notepad pentru corectare */ } } saveState(); $('#bulk-addresses').value = ''; $('#bulk-modal').hidden = true; drawMarkers(); refreshList(); setStatus(`${added} adrese adăugate`); }
function startBulkVoice() { const button = $('#bulk-voice'); const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition; if (!SpeechRecognition) { setStatus('Browserul nu suportă dictarea vocală.', true); return; } if (activeRecognition && activeMicButton === button) { stopActiveRecognition(); setStatus('Microfon oprit'); return; } stopActiveRecognition(); const recognition = new SpeechRecognition(); activeRecognition = recognition; activeMicButton = button; recognition.lang = 'ro-RO'; recognition.interimResults = false; button.classList.add('listening'); recognition.onresult = (event) => { const text = event.results[0][0].transcript; $('#bulk-addresses').value += `${$('#bulk-addresses').value ? '\n' : ''}${text}`; }; recognition.onerror = () => setStatus('Nu am putut înțelege adresa.', true); recognition.onend = () => { if (activeRecognition === recognition) stopActiveRecognition(); }; recognition.start(); setStatus('Ascult… apasă din nou pentru oprire'); }function showScanResult(text) { const result = $('#scan-result'); const field = $('#scan-text'); if (!result || !field) return; field.value = text.trim(); result.hidden = !field.value; field.focus(); }
function addScannedTextToList() { const value = $('#scan-text')?.value.trim(); if (!value) return; const bulk = $('#bulk-addresses'); bulk.value += `${bulk.value ? '\n' : ''}${value}`; $('#scan-result').hidden = true; setStatus('Adresa a fost adăugată în lista de scanare'); }
async function scanBulkImage(file) { if (!file) return; setStatus('Citesc eticheta…'); try { if ('BarcodeDetector' in window) { const detector = new BarcodeDetector(); const codes = await detector.detect(await createImageBitmap(file)); if (codes.length) { showScanResult(codes[0].rawValue); setStatus('Cod detectat — verifică textul'); return; } } if (!window.Tesseract) { await new Promise((resolve, reject) => { const script = document.createElement('script'); script.src = './ocr/tesseract.min.js'; script.onload = resolve; script.onerror = reject; document.head.append(script); }); } const result = await window.Tesseract.recognize(file, 'ron', { workerPath: './ocr/worker.min.js', corePath: './ocr/tesseract-core.wasm.js', langPath: './ocr/lang-data' }); const text = cleanOcrLines(result.data.text).join('\n'); showScanResult(text); setStatus('Text detectat — verifică textul'); } catch { setStatus('Nu am putut citi eticheta. Încearcă o fotografie mai clară.', true); } }
$('#copy-scan-text').addEventListener('click', async () => { const value = $('#scan-text').value.trim(); if (!value) return; try { await navigator.clipboard.writeText(value); setStatus('Text copiat'); } catch { $('#scan-text').select(); document.execCommand('copy'); setStatus('Text copiat'); } });
$('#add-scan-text').addEventListener('click', addScannedTextToList);
$('#clear-scan-text').addEventListener('click', () => { $('#scan-text').value = ''; $('#scan-result').hidden = true; });
$('#finish-route').addEventListener('click', () => { saveState(); window.location.href = 'routes.html'; });
$('#return-to-start').addEventListener('change', () => { saveState(); renderRouteDetails(); }); $('#service-time').addEventListener('change', saveState); $('#break-after')?.addEventListener('change', saveState); $('#break-duration')?.addEventListener('change', saveState); $('#departure-time').addEventListener('change', saveState); $('#optimization-mode')?.addEventListener('change', saveState); $('#vehicle-profile')?.addEventListener('change', saveState); $('#blocked-roads')?.addEventListener('change', () => { saveState(); refreshList(); });
async function refreshSavedRoutes() { const select = $('#saved-routes'); if (!select) return; const routes = await listSavedRoutes(); select.innerHTML = '<option value="">Rute salvate</option>'; routes.sort((a, b) => String(b.savedAt).localeCompare(String(a.savedAt))).forEach((route) => { const option = document.createElement('option'); option.value = route.id; option.textContent = `${route.name} · ${new Date(route.savedAt).toLocaleDateString('ro-RO')}`; select.append(option); }); }
$('#save-named-route')?.addEventListener('click', async () => { const name = $('#route-name').value.trim() || `Ruta ${new Date().toLocaleDateString('ro-RO')}`; await saveNamedRoute(name, { routeId: state.routeId || '', start: state.start, end: state.end, stops: state.stops, routeGeometry: state.routeGeometry, routeDistance: state.routeDistance || 0, routeDuration: state.routeDuration || 0, returnToStart: $('#return-to-start').checked, serviceTime: $('#service-time').value, breakAfter: $('#break-after')?.value || '0', breakDuration: $('#break-duration')?.value || '15', departureTime: $('#departure-time').value, optimizationMode: $('#optimization-mode')?.value || 'balanced', vehicleProfile: $('#vehicle-profile')?.value || 'car', trafficLevel: $('#traffic-level')?.value || 'normal', vehicleCapacity: Math.max(1, Number($('#vehicle-capacity')?.value || 50)), roadAvoidance: $('#road-avoidance')?.value || 'none', blockedRoads: $('#blocked-roads')?.value || '' }); await refreshSavedRoutes(); setStatus(`Ruta „${name}” a fost salvată local`); });
$('#load-named-route')?.addEventListener('click', async () => { const id = $('#saved-routes').value; if (!id) return; const route = (await listSavedRoutes()).find((item) => item.id === id); if (!route) return; applyImportedBackup(route.data); setStatus(`Ruta „${route.name}” a fost încărcată`); }); $('#delete-named-route')?.addEventListener('click', async () => { const id = $('#saved-routes').value; if (!id) { setStatus('Alege o rută salvată.', true); return; } const route = (await listSavedRoutes()).find((item) => item.id === id); if (!route || !window.confirm(`Ștergi ruta „${route.name}”?`)) return; await deleteSavedRoute(id); await refreshSavedRoutes(); setStatus('Ruta salvată a fost ștearsă'); });
loadPreferences(); loadState(); refreshAddressSuggestions(); drawMarkers(); refreshList(); refreshSavedRoutes();
async function recoverActiveRoute() { if (state.start || state.end || state.stops.length) return; const snapshot = await getActiveSnapshot(); if (!snapshot?.data?.stops?.length && !snapshot?.data?.start && !snapshot?.data?.end) return; if (!window.confirm('Am găsit o rută salvată automat. Vrei să o restaurezi?')) return; try { applyImportedBackup(snapshot.data); setStatus('Ruta salvată automat a fost restaurată'); } catch { setStatus('Ruta salvată automat nu a putut fi restaurată.', true); } }
recoverActiveRoute();
const toggleView = $('#toggle-view'); if (toggleView) toggleView.addEventListener('click', () => { const listView = $('#route-list-view'); const showingList = !listView.hidden; listView.hidden = showingList; $('#map').style.display = showingList ? 'block' : 'none'; $('.map-note').hidden = !showingList; toggleView.textContent = showingList ? 'Vezi lista' : 'Vezi harta'; if (showingList) setTimeout(() => map.invalidateSize(), 0); });

















function normalizeOcrLine(line) { return line.replace(/[|]/g, 'I').replace(/[–—]/g, '-').replace(/\s+/g, ' ').replace(/\b(Bucure[sș]ti|Bucuresti)\b/i, 'București').trim(); }
function extractPostalCode(line) { const match = line.match(/\b(\d{6})\b/); return match ? match[1] : ''; }
function cleanOcrLines(rawText) { return rawText.split(/\r?\n|\s*;\s*|\s+\|\s+/).map(normalizeOcrLine).filter((line) => line.length >= 5 && /\d|strada|șoseaua|bulevardul|calea|aleea|nr\.?|bl\.?/i.test(line)).map((line) => { const postalCode = extractPostalCode(line); return postalCode && !/cod poștal/i.test(line) ? `${line} (cod poștal ${postalCode})` : line; }); }
document.querySelector('#traffic-level')?.addEventListener('change', saveState);
['optimization-mode', 'vehicle-profile', 'traffic-level', 'vehicle-capacity'].forEach((id) => document.querySelector(`#${id}`)?.addEventListener('change', () => { if (state.start && state.stops.length) calculateRoute(); }));

['road-avoidance'].forEach((id) => document.querySelector(`#${id}`)?.addEventListener('change', () => { saveState(); if (state.start && state.stops.length) calculateRoute(); }));

