const map = L.map('map').setView([45.9432, 24.9668], 7);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; OpenStreetMap contributors' }).addTo(map);
const mapElement = document.getElementById('map');
let reviewMap = null; let reviewMarkers = [];
const resizeMap = () => map.invalidateSize({ pan: false });
window.addEventListener('resize', resizeMap);
if (window.ResizeObserver) new ResizeObserver(resizeMap).observe(mapElement);
setTimeout(resizeMap, 150);
const state = { start: null, end: null, stops: [], markers: [], routeLayer: null, editMode: false };
const $ = (selector) => document.querySelector(selector); const status = $('#status');
const STORAGE_KEY = 'route-optimizer-romania-v1';
const GEOCODE_CACHE_KEY = 'route-optimizer-geocode-cache-v1';
const ADDRESS_HISTORY_KEY = 'route-optimizer-address-history-v1';
function saveState() { localStorage.setItem(STORAGE_KEY, JSON.stringify({ start: state.start, end: state.end, stops: state.stops, returnToStart: $('#return-to-start').checked, serviceTime: $('#service-time').value })); }
function loadState() { try { const saved = JSON.parse(localStorage.getItem(STORAGE_KEY)); if (!saved) return; state.start = saved.start || null; state.end = saved.end || null; state.stops = Array.isArray(saved.stops) ? saved.stops : []; if (saved.returnToStart) $('#return-to-start').checked = true; if (saved.serviceTime !== undefined) $('#service-time').value = saved.serviceTime; if (state.start) $('#start-address').value = state.start.input || state.start.display_name; if (state.end) $('#end-address').value = state.end.input || state.end.display_name; } catch { localStorage.removeItem(STORAGE_KEY); } }
function formatDuration(totalMinutes) { const minutes = Math.max(0, Math.round(totalMinutes)); const hours = Math.floor(minutes / 60); const remainder = minutes % 60; if (!hours) return `${remainder} min`; if (!remainder) return `${hours} h`; return `${hours} h ${remainder} min`; }
function setStatus(message, error = false) { status.textContent = message; status.style.background = error ? '#4a2525' : '#123b34'; status.style.color = error ? '#ffb4b4' : '#6ee7c8'; }
function refreshList() {
  const list = $('#stops-list'); list.innerHTML = '';
  if (state.start) { const item = document.createElement('li'); item.className = 'start-item'; item.innerHTML = `<strong>Plecare</strong><small>${state.start.display_name}</small>`; list.append(item); }
  state.stops.forEach((stop, index) => { const item = document.createElement('li'); item.className = 'stop-item'; item.innerHTML = `<div><strong>${index + 1}. ${stop.display_name}</strong><small>${stop.serviceTime || 0} min staționare</small></div><span class="stop-actions"><button class="edit-stop" data-index="${index}" title="Editează oprirea">Editează</button><button class="remove-stop" data-index="${index}" title="Șterge oprirea">×</button></span>`; list.append(item); });
  if (state.end) { const item = document.createElement('li'); item.className = 'end-item'; item.innerHTML = `<strong>Final</strong><small>${state.end.display_name}</small>`; list.append(item); }
  $('#stop-count').textContent = state.stops.length; $('#summary').hidden = !state.stops.length; $('#optimize').disabled = !(state.start && state.stops.length);
  $('#review-route').hidden = !(state.start && state.stops.length);
  list.querySelectorAll('.remove-stop').forEach((button) => button.addEventListener('click', () => { state.stops.splice(Number(button.dataset.index), 1); saveState(); drawMarkers(); refreshList(); setStatus('Oprire ștearsă'); }));
  list.querySelectorAll('.edit-stop').forEach((button) => button.addEventListener('click', () => { const stop = state.stops[Number(button.dataset.index)]; $('#stop-address').value = stop.input || stop.display_name; state.stops.splice(Number(button.dataset.index), 1); saveState(); drawMarkers(); refreshList(); $('#stop-address').focus(); setStatus('Editează adresa și apasă Adaugă'); }));
  renderRouteDetails();
}
function renderReview() { const list = $('#review-items'); list.innerHTML = ''; if (state.start) { const item = document.createElement('li'); item.innerHTML = `<strong>Start</strong><small>${state.start.display_name}</small>`; list.append(item); } state.stops.forEach((stop, index) => { const item = document.createElement('li'); item.innerHTML = `<strong>Stop ${index + 1}</strong><small>${stop.display_name}</small>`; list.append(item); }); const end = state.end || ($('#return-to-start').checked ? state.start : null); if (end) { const item = document.createElement('li'); item.innerHTML = `<strong>Finish</strong><small>${end.display_name}</small>`; list.append(item); } }
function renderReviewMap() { if (!reviewMap) { reviewMap = L.map('review-map').setView([45.9432, 24.9668], 7); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; OpenStreetMap contributors' }).addTo(reviewMap); } reviewMarkers.forEach((marker) => marker.remove()); reviewMarkers = []; const pin = (color, label) => L.divIcon({ className: 'pin-icon', html: `<svg viewBox="0 0 38 48" aria-hidden="true"><path d="M19 1C9.1 1 1.5 8.4 1.5 17.5 1.5 29.5 19 47 19 47s17.5-17.5 17.5-29.5C36.5 8.4 28.9 1 19 1Z" fill="${color}" stroke="#f3fffb" stroke-width="2"/><text x="19" y="21" text-anchor="middle" fill="#fff" font-size="11" font-weight="800" font-family="Arial, sans-serif">${label}</text></svg>`, iconSize: [38, 48], iconAnchor: [19, 47] }); if (state.start) reviewMarkers.push(L.marker([state.start.lat, state.start.lon], { icon: pin('#e08a20', 'S') }).addTo(reviewMap)); state.stops.forEach((stop, index) => reviewMarkers.push(L.marker([stop.lat, stop.lon], { icon: pin('#0f8f7b', index + 1) }).addTo(reviewMap))); const end = state.end || ($('#return-to-start').checked ? state.start : null); if (end) reviewMarkers.push(L.marker([end.lat, end.lon], { icon: pin('#c84b63', 'F') }).addTo(reviewMap)); const points = [state.start, ...state.stops, end].filter(Boolean); if (points.length > 1) reviewMap.fitBounds(L.latLngBounds(points.map((point) => [point.lat, point.lon])).pad(.15)); setTimeout(() => reviewMap.invalidateSize(), 50); }
function renderRouteDetails() {
  const details = $('#route-details'); if (!details) return; details.innerHTML = '';
  const addRow = (label, point, className = '', stopIndex = null) => { if (!point) return; const item = document.createElement('li'); item.className = className; item.innerHTML = `<strong>${label}</strong><span>${point.display_name}</span>${state.editMode && stopIndex !== null ? `<div class="order-actions"><label>Poziția <input class="position-input" type="number" min="1" max="${state.stops.length}" value="${stopIndex + 1}" data-index="${stopIndex}" /><button data-move-to data-index="${stopIndex}">Mută</button></label><button data-move="up" data-index="${stopIndex}" ${stopIndex === 0 ? 'disabled' : ''}>↑</button><button data-move="down" data-index="${stopIndex}" ${stopIndex === state.stops.length - 1 ? 'disabled' : ''}>↓</button></div>` : ''}`; details.append(item); };
  addRow('Start', state.start, 'route-start'); state.stops.forEach((stop, index) => addRow(`Stop ${index + 1}`, stop, '', index)); addRow('Finish', state.end || (state.start && $('#return-to-start').checked ? state.start : null), 'route-finish');
  details.querySelectorAll('[data-move]').forEach((button) => button.addEventListener('click', () => { const index = Number(button.dataset.index); const target = button.dataset.move === 'up' ? index - 1 : index + 1; if (target < 0 || target >= state.stops.length) return; [state.stops[index], state.stops[target]] = [state.stops[target], state.stops[index]]; saveState(); drawMarkers(); refreshList(); setStatus('Ordinea a fost schimbată'); }));
  details.querySelectorAll('[data-move-to]').forEach((button) => button.addEventListener('click', () => { const index = Number(button.dataset.index); const input = details.querySelector(`.position-input[data-index="${index}"]`); const target = Number(input.value) - 1; if (!Number.isInteger(target) || target < 0 || target >= state.stops.length) { setStatus(`Poziția trebuie să fie între 1 și ${state.stops.length}.`, true); return; } const [stop] = state.stops.splice(index, 1); state.stops.splice(target, 0, stop); saveState(); drawMarkers(); refreshList(); setStatus('Stop mutat și renumerotat'); }));
  $('#list-route-status').textContent = state.stops.length ? `${state.stops.length} opriri · ${$('#route-distance').textContent} · ${$('#route-duration').textContent}` : 'Adresele introduse';
}
function drawMarkers() {
  state.markers.forEach((marker) => marker.remove()); state.markers = [];
  const pinIcon = (color, label) => L.divIcon({ className: 'pin-icon', html: `<svg viewBox="0 0 38 48" aria-hidden="true"><path d="M19 1C9.1 1 1.5 8.4 1.5 17.5 1.5 29.5 19 47 19 47s17.5-17.5 17.5-29.5C36.5 8.4 28.9 1 19 1Z" fill="${color}" stroke="#f3fffb" stroke-width="2"/><circle cx="19" cy="17" r="10" fill="#ffffff33"/><text x="19" y="21" text-anchor="middle" fill="#fff" font-size="11" font-weight="800" font-family="Arial, sans-serif">${label}</text></svg>`, iconSize: [38, 48], iconAnchor: [19, 47] });
  const startIcon = pinIcon('#e08a20', 'S');
  const stopIcon = (number) => pinIcon('#0f8f7b', number);
  const endIcon = pinIcon('#c84b63', 'F');
  if (state.start) state.markers.push(L.marker([state.start.lat, state.start.lon], { icon: startIcon, zIndexOffset: 1000 }).addTo(map).bindPopup(`<b>Start</b><br>${state.start.display_name}`));
  state.stops.forEach((stop, index) => state.markers.push(L.marker([stop.lat, stop.lon], { icon: stopIcon(index + 1) }).addTo(map).bindPopup(`<b>Oprirea ${index + 1}</b><br>${stop.display_name}`)));
  if (state.end) state.markers.push(L.marker([state.end.lat, state.end.lon], { icon: endIcon, zIndexOffset: 900 }).addTo(map).bindPopup(`<b>Final</b><br>${state.end.display_name}`));
  const all = [state.start, ...state.stops, state.end].filter(Boolean); if (all.length > 1) map.fitBounds(L.latLngBounds(all.map((point) => [point.lat, point.lon])).pad(.15));
}
async function geocode(address) {
  const normalized = address.trim().toLowerCase();
  let cache = {}; try { cache = JSON.parse(localStorage.getItem(GEOCODE_CACHE_KEY) || '{}'); } catch { cache = {}; }
  if (cache[normalized]) return { ...cache[normalized], input: address };  const url = `https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&countrycodes=ro&q=${encodeURIComponent(`${address}, România`)}`;
  const response = await fetch(url, { headers: { Accept: 'application/json' } }); if (!response.ok) throw new Error('Serviciul de căutare nu răspunde momentan.'); const results = await response.json(); if (!results.length) throw new Error(`Nu am găsit adresa „${address}”.`);
  const location = { lat: Number(results[0].lat), lon: Number(results[0].lon), display_name: results[0].display_name }; cache[normalized] = location; localStorage.setItem(GEOCODE_CACHE_KEY, JSON.stringify(cache)); return { ...location, input: address };
}
function refreshAddressSuggestions() { const datalist = $('#address-suggestions'); if (!datalist) return; let history = []; try { history = JSON.parse(localStorage.getItem(ADDRESS_HISTORY_KEY) || '[]'); } catch { history = []; } datalist.innerHTML = ''; history.slice(0, 20).forEach((address) => { const option = document.createElement('option'); option.value = address; datalist.append(option); }); }
function rememberAddress(address) { if (!address) return; let history = []; try { history = JSON.parse(localStorage.getItem(ADDRESS_HISTORY_KEY) || '[]'); } catch { history = []; } history = [address, ...history.filter((item) => item.toLowerCase() !== address.toLowerCase())].slice(0, 50); localStorage.setItem(ADDRESS_HISTORY_KEY, JSON.stringify(history)); refreshAddressSuggestions(); }async function addAddress(kind) {
  const input = kind === 'start' ? $('#start-address') : kind === 'end' ? $('#end-address') : $('#stop-address'); const address = input.value.trim(); if (!address) return; setStatus('Caut adresa…'); input.disabled = true;
  try { const location = await geocode(address); location.input = address; rememberAddress(address); if (kind === 'start') state.start = location; else if (kind === 'end') state.end = location; else { const duplicate = state.stops.some((stop) => Math.abs(stop.lat - location.lat) < 0.0001 && Math.abs(stop.lon - location.lon) < 0.0001); if (duplicate) throw new Error('Această oprire există deja în rută.'); state.stops.push({ ...location, serviceTime: Number($('#service-time').value) || 0 }); input.value = ''; } saveState(); drawMarkers(); refreshList(); setStatus(kind === 'start' ? 'Start setat și salvat' : kind === 'end' ? 'Finish setat și salvat' : 'Oprire adăugată'); } catch (error) { setStatus(error.message, true); } finally { input.disabled = false; input.focus(); }
}
function useCurrentLocation(kind = 'start') {
  if (!navigator.geolocation) { setStatus('Browserul nu oferă locația GPS.', true); return; } setStatus('Obțin locația exactă…');
  navigator.geolocation.getCurrentPosition(({ coords }) => { const location = { lat: coords.latitude, lon: coords.longitude, display_name: 'Locația GPS curentă a curierului', input: 'Locația GPS curentă' }; if (kind === 'end') { state.end = location; $('#end-address').value = location.display_name; } else { state.start = location; $('#start-address').value = location.display_name; } saveState(); drawMarkers(); refreshList(); setStatus(kind === 'end' ? 'Finish GPS setat și salvat' : 'Start GPS setat și salvat'); }, () => setStatus('Nu am putut obține locația. Verifică permisiunea GPS.', true), { enableHighAccuracy: true, timeout: 10000 });
}
function routeCost(order, matrix, closeLoop) { let cost = 0; for (let i = 0; i < order.length - 1; i += 1) cost += matrix[order[i]][order[i + 1]] || Infinity; if (closeLoop && order.length > 1) cost += matrix[order[order.length - 1]][order[0]] || Infinity; return cost; }
function improveOrder(order, matrix, closeLoop, fixedEnd) {
  let improved = true; let currentCost = routeCost(order, matrix, closeLoop); let passes = 0;
  while (improved && passes < 40) { improved = false; passes += 1; const lastReversible = fixedEnd ? order.length - 2 : order.length - 1;
    for (let i = 1; i < lastReversible; i += 1) for (let k = i + 1; k <= lastReversible; k += 1) { const candidate = order.slice(0, i).concat(order.slice(i, k + 1).reverse(), order.slice(k + 1)); const candidateCost = routeCost(candidate, matrix, closeLoop); if (candidateCost + 1 < currentCost) { order = candidate; currentCost = candidateCost; improved = true; } }
  }
  return order;
}
async function calculateRoute() {
  if (!state.start || !state.stops.length) return; setStatus('Calculez timpii și optimizez traseul…');
  const points = [state.start, ...state.stops, ...(state.end ? [state.end] : [])]; const fixedEnd = Boolean(state.end); const closeLoop = !fixedEnd && $('#return-to-start').checked;
  try {
    const coordinates = points.map((point) => `${point.lon},${point.lat}`).join(';'); const tableResponse = await fetch(`https://router.project-osrm.org/table/v1/driving/${coordinates}?annotations=duration`); const table = await tableResponse.json(); if (!table.durations) throw new Error('Nu am putut calcula timpii dintre opriri.');
    const matrix = table.durations; const endIndex = fixedEnd ? points.length - 1 : null; const remaining = []; for (let index = 1; index < points.length; index += 1) if (index !== endIndex) remaining.push(index);
    const order = [0]; let current = 0; while (remaining.length) { let bestAt = 0; for (let index = 1; index < remaining.length; index += 1) if ((matrix[current][remaining[index]] ?? Infinity) < (matrix[current][remaining[bestAt]] ?? Infinity)) bestAt = index; current = remaining.splice(bestAt, 1)[0]; order.push(current); }
    if (fixedEnd) order.push(endIndex); const optimizedOrder = improveOrder(order, matrix, closeLoop, fixedEnd); const routePoints = optimizedOrder.map((index) => points[index]); if (closeLoop) routePoints.push(points[0]);
    const routeCoordinates = routePoints.map((point) => `${point.lon},${point.lat}`).join(';'); const routeResponse = await fetch(`https://router.project-osrm.org/route/v1/driving/${routeCoordinates}?overview=full&geometries=geojson&steps=false`); const routeData = await routeResponse.json(); if (!routeData.routes?.length) throw new Error('Nu am putut desena ruta optimizată.'); const route = routeData.routes[0];
    state.stops = optimizedOrder.slice(1, fixedEnd ? -1 : undefined).map((index) => points[index]); if (state.routeLayer) state.routeLayer.remove(); state.routeLayer = L.geoJSON(route.geometry, { style: { color: '#0f766e', weight: 5, opacity: .85 } }).addTo(map);
    const serviceMinutes = state.stops.reduce((sum, stop) => sum + (stop.serviceTime || 0), 0); $('#route-distance').textContent = `${(route.distance / 1000).toFixed(1)} km`; $('#route-duration').textContent = formatDuration(Math.round(route.duration / 60) + serviceMinutes); saveState(); $('#finish-route').hidden = false; drawMarkers(); refreshList(); map.fitBounds(state.routeLayer.getBounds().pad(.12)); setStatus('Rută optimizată');
  } catch (error) { setStatus(error.message, true); }
}
function openNavigation(index) { const stop = state.stops[index]; if (stop) window.open(`https://www.google.com/maps/dir/?api=1&destination=${stop.lat},${stop.lon}`, '_blank', 'noopener'); }
function exportCsv() { const rows = [['ordine', 'adresa', 'latitudine', 'longitudine', 'minute_stationare', 'livrat']]; state.stops.forEach((stop, index) => rows.push([index + 1, stop.input || stop.display_name, stop.lat, stop.lon, stop.serviceTime || 0, stop.delivered ? 'da' : 'nu'])); const csv = rows.map((row) => row.map((value) => `"${String(value).replaceAll('"', '""')}"`).join(';')).join('\n'); const blob = new Blob([`\ufeff${csv}`], { type: 'text/csv;charset=utf-8' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `ruta-${new Date().toISOString().slice(0, 10)}.csv`; link.click(); URL.revokeObjectURL(link.href); }
function downloadFile(name, content, type) { const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([content], { type })); link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 500); }
function exportBackup() { downloadFile(`route-optimizer-backup-${new Date().toISOString().slice(0, 10)}.json`, JSON.stringify({ version: 1, savedAt: new Date().toISOString(), start: state.start, end: state.end, stops: state.stops, returnToStart: $('#return-to-start').checked, serviceTime: $('#service-time').value }, null, 2), 'application/json'); setStatus('Backup salvat'); }
function applyImportedBackup(data) { if (!data || !Array.isArray(data.stops)) throw new Error('Fișierul nu este un backup valid.'); state.start = data.start || null; state.end = data.end || null; state.stops = data.stops; $('#return-to-start').checked = Boolean(data.returnToStart); if (data.serviceTime !== undefined) $('#service-time').value = data.serviceTime; $('#start-address').value = state.start?.input || state.start?.display_name || ''; $('#end-address').value = state.end?.input || state.end?.display_name || ''; saveState(); drawMarkers(); refreshList(); setStatus('Backup încărcat'); }
$('#set-start').addEventListener('click', () => addAddress('start')); $('#set-end').addEventListener('click', () => addAddress('end')); $('#add-stop').addEventListener('click', () => addAddress('stop')); $('#current-start-location').addEventListener('click', () => useCurrentLocation('start')); $('#current-end-location').addEventListener('click', () => useCurrentLocation('end')); $('#start-address').addEventListener('keydown', (event) => { if (event.key === 'Enter') addAddress('start'); }); $('#end-address').addEventListener('keydown', (event) => { if (event.key === 'Enter') addAddress('end'); }); $('#stop-address').addEventListener('keydown', (event) => { if (event.key === 'Enter') addAddress('stop'); }); $('#optimize').addEventListener('click', calculateRoute);
$('#csv-file').addEventListener('change', async (event) => { const file = event.target.files[0]; if (!file) return; const rows = (await file.text()).split(/\r?\n/).map((line) => line.trim()).filter(Boolean); setStatus(`Import ${rows.length} adrese…`); for (const row of rows) { try { const location = await geocode(row.split(';')[0]); state.stops.push({ ...location, serviceTime: Number($('#service-time').value) || 0 }); } catch { /* ignoră rândurile invalide */ } } saveState(); drawMarkers(); refreshList(); setStatus('Import finalizat'); event.target.value = ''; });
$('#clear-all').addEventListener('click', () => { state.start = null; state.end = null; state.stops = []; localStorage.removeItem(STORAGE_KEY); $('#start-address').value = ''; $('#end-address').value = ''; state.markers.forEach((marker) => marker.remove()); state.markers = []; if (state.routeLayer) state.routeLayer.remove(); state.routeLayer = null; $('#route-distance').textContent = '—'; $('#route-duration').textContent = '—'; refreshList(); setStatus('Pregătit'); });
$('#export-csv').addEventListener('click', exportCsv);
$('#toggle-edit-order').addEventListener('click', () => { state.editMode = !state.editMode; $('#toggle-edit-order').textContent = state.editMode ? 'Gata cu editarea' : 'Editează ordinea'; renderRouteDetails(); });
$('#export-backup').addEventListener('click', exportBackup); $('#import-backup-button').addEventListener('click', () => $('#import-backup').click()); $('#import-backup').addEventListener('change', async (event) => { const file = event.target.files[0]; if (!file) return; try { applyImportedBackup(JSON.parse(await file.text())); } catch (error) { setStatus(error.message || 'Backup invalid.', true); } event.target.value = ''; });
$('#review-route').addEventListener('click', () => { renderReview(); $('#review-modal').hidden = false; }); $('#back-to-entry').addEventListener('click', () => { $('#review-modal').hidden = true; }); $('#toggle-review-map').addEventListener('click', () => { const showingMap = !$('#review-map').hidden; $('#review-map').hidden = showingMap; $('#review-items').hidden = !showingMap; $('#toggle-review-map').textContent = showingMap ? 'Vezi harta' : 'Vezi adresele'; if (!showingMap) renderReviewMap(); }); $('#optimize-from-review').addEventListener('click', async () => { await calculateRoute(); if (!$('#finish-route').hidden) $('#review-modal').hidden = true; });
$('#bulk-add').addEventListener('click', () => { $('#bulk-modal').hidden = false; $('#bulk-addresses').focus(); }); $('#close-bulk').addEventListener('click', () => { $('#bulk-modal').hidden = true; }); $('#bulk-done').addEventListener('click', addBulkAddresses); $('#bulk-voice').addEventListener('click', startBulkVoice); $('#bulk-camera').addEventListener('click', () => $('#bulk-image').click()); $('#bulk-image').addEventListener('change', (event) => { scanBulkImage(event.target.files[0]); event.target.value = ''; });
function startVoiceInput(inputId, button) { const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition; if (!SpeechRecognition) { setStatus('Browserul nu suportă dictarea vocală.', true); return; } const input = document.getElementById(inputId); const recognition = new SpeechRecognition(); recognition.lang = 'ro-RO'; recognition.interimResults = false; recognition.maxAlternatives = 1; button.classList.add('listening'); setStatus('Ascult… spune adresa completă'); recognition.onresult = (event) => { input.value = event.results[0][0].transcript; input.focus(); }; recognition.onerror = () => setStatus('Nu am putut înțelege adresa. Încearcă din nou.', true); recognition.onend = () => button.classList.remove('listening'); recognition.start(); }
document.querySelectorAll('.mic-button').forEach((button) => button.addEventListener('click', () => startVoiceInput(button.dataset.input, button)));
async function addBulkAddresses() { const lines = $('#bulk-addresses').value.split(/\r?\n/).map((line) => line.trim()).filter(Boolean); if (!lines.length) { setStatus('Adaugă cel puțin o adresă.', true); return; } setStatus(`Caut ${lines.length} adrese…`); let added = 0; for (const address of lines) { try { const location = await geocode(address); const duplicate = state.stops.some((stop) => Math.abs(stop.lat - location.lat) < 0.0001 && Math.abs(stop.lon - location.lon) < 0.0001); if (!duplicate) { state.stops.push({ ...location, input: address, serviceTime: Number($('#service-time').value) || 0 }); added += 1; } } catch { /* adresa rămâne în notepad pentru corectare */ } } saveState(); $('#bulk-addresses').value = ''; $('#bulk-modal').hidden = true; drawMarkers(); refreshList(); setStatus(`${added} adrese adăugate`); }
function startBulkVoice() { const SpeechRecognition = window.SpeechRecognition || window.webkitSpeechRecognition; if (!SpeechRecognition) { setStatus('Browserul nu suportă dictarea vocală.', true); return; } const recognition = new SpeechRecognition(); recognition.lang = 'ro-RO'; recognition.interimResults = false; recognition.onresult = (event) => { const text = event.results[0][0].transcript; $('#bulk-addresses').value += `${$('#bulk-addresses').value ? '\n' : ''}${text}`; }; recognition.onerror = () => setStatus('Nu am putut înțelege adresa.', true); recognition.start(); setStatus('Ascult… spune o adresă'); }
async function scanBulkImage(file) { if (!file) return; setStatus('Citesc eticheta…'); try { if ('BarcodeDetector' in window) { const detector = new BarcodeDetector(); const codes = await detector.detect(await createImageBitmap(file)); if (codes.length) { $('#bulk-addresses').value += `${$('#bulk-addresses').value ? '\n' : ''}${codes[0].rawValue}`; setStatus('Codul a fost adăugat în notepad'); return; } } if (!window.Tesseract) { await new Promise((resolve, reject) => { const script = document.createElement('script'); script.src = 'https://cdn.jsdelivr.net/npm/tesseract.js@5/dist/tesseract.min.js'; script.onload = resolve; script.onerror = reject; document.head.append(script); }); } const result = await window.Tesseract.recognize(file, 'ron+eng'); const text = result.data.text.split(/\r?\n/).map((line) => line.trim()).filter(Boolean).join('\n'); $('#bulk-addresses').value += `${$('#bulk-addresses').value ? '\n' : ''}${text}`; setStatus('Textul a fost adăugat în notepad'); } catch { setStatus('Nu am putut citi eticheta. Încearcă o fotografie mai clară.', true); } }
$('#finish-route').addEventListener('click', () => { saveState(); window.location.href = 'routes.html'; });
$('#return-to-start').addEventListener('change', () => { saveState(); renderRouteDetails(); }); $('#service-time').addEventListener('change', saveState);
loadState(); refreshAddressSuggestions(); drawMarkers(); refreshList();
const toggleView = $('#toggle-view'); if (toggleView) toggleView.addEventListener('click', () => { const listView = $('#route-list-view'); const showingList = !listView.hidden; listView.hidden = showingList; $('#map').style.display = showingList ? 'block' : 'none'; $('.map-note').hidden = !showingList; toggleView.textContent = showingList ? 'Vezi lista' : 'Vezi harta'; if (showingList) setTimeout(() => map.invalidateSize(), 0); });

