import { listCompletedStops, saveCompletedStop, clearCompletedStops } from './storage.js';
const KEY = 'route-optimizer-completed-v1';
const list = document.querySelector('#history-list');
const empty = document.querySelector('#empty-history');
const stats = document.querySelector('#history-stats');
const filter = document.querySelector('#history-filter');
let activeFilter = 'all';
const allowedStatuses = new Set(['delivered', 'absent', 'wrong-address', 'rescheduled', 'cancelled']);
async function readHistory() { const indexed = await listCompletedStops(); if (indexed.length) return indexed; let legacy = []; try { legacy = JSON.parse(localStorage.getItem(KEY) || '[]'); } catch { legacy = []; } for (const stop of legacy) await saveCompletedStop(stop); return legacy; }
function addText(parent, tag, value, className = '') { const node = document.createElement(tag); if (className) node.className = className; node.textContent = value || ''; parent.append(node); return node; }
async function render() { const history = await readHistory(); const visible = activeFilter === 'all' ? history : history.filter((stop) => (stop.status || 'delivered') === activeFilter); list.replaceChildren(); empty.hidden = visible.length > 0; const counts = visible.reduce((result, stop) => { const key = stop.statusLabel || 'Livrat'; result[key] = (result[key] || 0) + 1; return result; }, {}); if (stats) { stats.replaceChildren(); Object.entries(counts).forEach(([label, count]) => { const card = document.createElement('span'); addText(card, 'strong', String(count)); addText(card, 'small', label); stats.append(card); }); } const groups = new Map(); visible.slice().reverse().forEach((stop) => { const timestamp = new Date(stop.historyAt || stop.deliveredAt || Date.now()); const dayKey = timestamp.toLocaleDateString('ro-RO', { year: 'numeric', month: 'long', day: 'numeric' }); if (!groups.has(dayKey)) groups.set(dayKey, []); groups.get(dayKey).push({ stop, timestamp }); }); groups.forEach((items, day) => { const heading = document.createElement('li'); heading.className = 'history-day'; addText(heading, 'strong', day); list.append(heading); items.forEach(({ stop, timestamp }) => { const item = document.createElement('li'); const status = allowedStatuses.has(stop.status) ? stop.status : 'delivered'; item.className = `history-entry status-${status}`; addText(item, 'strong', stop.input || stop.display_name || 'Adresă'); addText(item, 'small', `${stop.statusLabel || 'Livrat'} · ${timestamp.toLocaleTimeString('ro-RO', { hour: '2-digit', minute: '2-digit' })}`); if (stop.actualServiceMinutes) addText(item, 'small', `Timp la oprire: ${stop.actualServiceMinutes} min`); if (stop.note) addText(item, 'small', `Notiță: ${stop.note}`); list.append(item); }); }); }
filter?.addEventListener('change', () => { activeFilter = filter.value; render(); });
document.querySelector('#export-history')?.addEventListener('click', async () => { const history = await readHistory(); const rows = [['data', 'ora', 'adresa', 'status', 'notita', 'timp_oprire_min', 'cod_postal', 'latitudine', 'longitudine']]; history.forEach((stop) => { const timestamp = new Date(stop.historyAt || stop.deliveredAt || Date.now()); rows.push([timestamp.toLocaleDateString('ro-RO'), timestamp.toLocaleTimeString('ro-RO', { hour: '2-digit', minute: '2-digit' }), stop.input || stop.display_name || '', stop.statusLabel || 'Livrat', stop.note || '', stop.actualServiceMinutes || '', stop.postalCode || stop.address?.postcode || '', stop.lat ?? '', stop.lon ?? '']); }); const csv = rows.map((row) => row.map((value) => `"${String(value).replaceAll('"', '""')}"`).join(';')).join('\n'); const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob(['\ufeff' + csv], { type: 'text/csv;charset=utf-8' })); link.download = 'istoric-stopuri-' + new Date().toISOString().slice(0, 10) + '.csv'; link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 500); });
document.querySelector('#clear-history').addEventListener('click', async () => { if (confirm('Ștergi tot istoricul local?')) { localStorage.removeItem(KEY); await clearCompletedStops(); render(); } });
render();
