import { saveSnapshot } from './storage.js';
const STORAGE_KEY = 'route-optimizer-romania-v1';
const COMPLETED_KEY = 'route-optimizer-completed-v1';
const saved = JSON.parse(localStorage.getItem(STORAGE_KEY) || 'null');
const state = saved || { start: null, end: null, stops: [], returnToStart: false };
const map = L.map('route-map').setView([45.9432, 24.9668], 7);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; OpenStreetMap contributors' }).addTo(map);
const $ = (selector) => document.querySelector(selector);
function save() { localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); saveSnapshot(state); }
function pinIcon(color, label) { return L.divIcon({ className: 'pin-icon', html: `<svg viewBox="0 0 38 48" aria-hidden="true"><path d="M19 1C9.1 1 1.5 8.4 1.5 17.5 1.5 29.5 19 47 19 47s17.5-17.5 17.5-29.5C36.5 8.4 28.9 1 19 1Z" fill="${color}" stroke="#f3fffb" stroke-width="2"/><circle cx="19" cy="17" r="10" fill="#ffffff33"/><text x="19" y="21" text-anchor="middle" fill="#fff" font-size="11" font-weight="800" font-family="Arial, sans-serif">${label}</text></svg>`, iconSize: [38, 48], iconAnchor: [19, 47] }); }
function renderList() { const list = $('#delivery-list'); list.innerHTML = ''; if (state.start) { const start = document.createElement('li'); start.className = 'delivery-item'; start.innerHTML = `<div><strong>Start</strong><span>${state.start.display_name}</span></div>`; list.append(start); } state.stops.filter((stop) => !stop.delivered).forEach((stop, index) => { const item = document.createElement('li'); item.className = `delivery-item${stop.delivered ? ' delivered' : ''}`; item.innerHTML = `<div><strong>Stop ${index + 1}</strong><span>${stop.display_name}${stop.etaLabel ? `<small class="eta-label">Sosire estimată: ${stop.etaLabel}</small>` : ''}${stop.statusLabel ? `<small class="status-badge status-${stop.status}">${stop.statusLabel}</small>` : ''}${stop.note ? `<small>Notiță: ${stop.note}</small>` : ''}</span></div>${stop.delivered ? '<span class="delivered-label">Livrat</span>' : `<button class="deliver-button" data-index="${state.stops.indexOf(stop)}">Marchează stop</button>`}`; list.append(item); }); if (state.end || (state.returnToStart && state.start)) { const finish = document.createElement('li'); finish.className = 'delivery-item'; const end = state.end || state.start; finish.innerHTML = `<div><strong>Finish</strong><span>${end.display_name}${end.etaLabel ? `<small class="eta-label">Sosire estimată: ${end.etaLabel}</small>` : ''}</span></div>`; list.append(finish); } const delivered = state.stops.filter((stop) => stop.delivered).length; $('#route-meta').textContent = `${state.stops.length} opriri · ${delivered} livrate`; list.querySelectorAll('.deliver-button').forEach((button) => button.addEventListener('click', () => { openStatusEditor(Number(button.dataset.index)); })); }
const STATUS_LABELS = { delivered: 'Livrat', absent: 'Client absent', 'wrong-address': 'Adresă greșită', rescheduled: 'Reprogramat', cancelled: 'Anulat' };
function openStatusEditor(index) { const stop = state.stops[index]; if (!stop) return; $('#delivery-status').value = stop.status || (stop.delivered ? 'delivered' : 'delivered'); $('#delivery-note').value = stop.note || ''; $('#delivery-status-modal').dataset.index = String(index); $('#delivery-status-modal').hidden = false; $('#delivery-status').focus(); }
function recalculateRemainingEta() { const delivered = state.stops.filter((stop) => stop.delivered && stop.deliveredAt && stop.etaAt); if (!delivered.length) return; const latest = delivered.reduce((a, b) => new Date(a.deliveredAt) > new Date(b.deliveredAt) ? a : b); const delay = Math.max(0, Date.now() - new Date(latest.etaAt).getTime()); if (!delay) return; state.stops.filter((stop) => !stop.delivered && stop.etaAt).forEach((stop) => { stop.etaAt += delay; stop.etaLabel = new Intl.DateTimeFormat('ro-RO', { hour: '2-digit', minute: '2-digit' }).format(new Date(stop.etaAt)); }); if (state.end?.etaAt) { state.end.etaAt += delay; state.end.etaLabel = new Intl.DateTimeFormat('ro-RO', { hour: '2-digit', minute: '2-digit' }).format(new Date(state.end.etaAt)); } }function saveStatusEditor() { const modal = $('#delivery-status-modal'); const index = Number(modal.dataset.index); const stop = state.stops[index]; if (!stop) return; const status = $('#delivery-status').value; stop.status = status; stop.delivered = status === 'delivered'; stop.note = $('#delivery-note').value.trim(); stop.statusLabel = STATUS_LABELS[status]; stop.updatedAt = new Date().toISOString(); if (stop.delivered) { stop.deliveredAt = stop.updatedAt; navigator.vibrate?.(35); const history = JSON.parse(localStorage.getItem(COMPLETED_KEY) || '[]'); history.push({ ...stop }); localStorage.setItem(COMPLETED_KEY, JSON.stringify(history)); } recalculateRemainingEta(); save(); modal.hidden = true; renderList(); updateProgress(); drawMap(); }function updateProgress() { const total = state.stops.length; const delivered = state.stops.filter((stop) => stop.delivered).length; const nextStop = state.stops.find((stop) => !stop.delivered); const finish = total > 0 && !nextStop && state.end ? { ...state.end, isFinish: true } : null; const next = nextStop || finish; $('#progress-label').textContent = `${delivered} / ${total} livrate`; $('#progress-percent').textContent = `${total ? Math.round((delivered / total) * 100) : 0}%`; $('#progress-bar').style.width = `${total ? (delivered / total) * 100 : 0}%`; $('#next-stop-card').hidden = !next; if (next) { $('#next-stop-address').textContent = `${next.display_name}${next.etaLabel ? ` · Sosire estimată ${next.etaLabel}` : ''}`; $('#next-label').textContent = next.isFinish ? 'FINISH' : 'URMĂTOAREA OPRIRE'; } $('#finish-job').hidden = !(total > 0 && delivered === total); }
let routeMarkers = []; function drawMap() { routeMarkers.forEach((marker) => marker.remove()); routeMarkers = []; if (state.start) routeMarkers.push(L.marker([state.start.lat, state.start.lon], { icon: pinIcon('#e08a20', 'S'), zIndexOffset: 1000 }).addTo(map)); state.stops.forEach((stop, index) => routeMarkers.push(L.marker([stop.lat, stop.lon], { icon: pinIcon(stop.delivered ? '#c84b63' : '#0f8f7b', index + 1) }).addTo(map))); const end = state.end || (state.returnToStart ? state.start : null); if (end) routeMarkers.push(L.marker([end.lat, end.lon], { icon: pinIcon('#c84b63', 'F'), zIndexOffset: 900 }).addTo(map)); const points = [state.start, ...state.stops, end].filter(Boolean); if (points.length > 1) map.fitBounds(L.latLngBounds(points.map((point) => [point.lat, point.lon])).pad(.1), { maxZoom: 16 }); else if (points.length === 1) map.setView([points[0].lat, points[0].lon], 15); }
$('#recalculate').addEventListener('click', () => { state.stops = state.stops.filter((stop) => !stop.delivered); save(); window.location.href = 'index.html?recalculate=1'; });
$('#reset-delivered').addEventListener('click', () => { state.stops.forEach((stop) => { stop.delivered = false; }); save(); renderList(); updateProgress(); drawMap(); });
function nextStop() { const next = state.stops.find((stop) => !stop.delivered); return next || (state.end ? { ...state.end, isFinish: true } : null); }
const preferredNavigation = $('#preferred-navigation'); preferredNavigation.value = localStorage.getItem('route-optimizer-navigation') || 'ask'; preferredNavigation.addEventListener('change', () => localStorage.setItem('route-optimizer-navigation', preferredNavigation.value)); function openPreferredNavigation(stop, choice) { if (!stop) return; if (choice === 'apple') window.open(`https://maps.apple.com/?daddr=${stop.lat},${stop.lon}&dirflg=d`, '_blank', 'noopener'); else if (choice === 'waze') window.open(`https://waze.com/ul?ll=${stop.lat}%2C${stop.lon}&navigate=yes`, '_blank', 'noopener'); else window.open(`https://www.google.com/maps/dir/?api=1&destination=${stop.lat},${stop.lon}`, '_blank', 'noopener'); }
$('#navigate-next').addEventListener('click', () => { const choice = preferredNavigation.value; const stop = nextStop(); if (choice !== 'ask') { openPreferredNavigation(stop, choice); return; } $('#navigation-options').hidden = !$('#navigation-options').hidden; }); $('#open-google-maps').addEventListener('click', () => { const stop = nextStop(); if (stop) window.open(`https://www.google.com/maps/dir/?api=1&destination=${stop.lat},${stop.lon}`, '_blank', 'noopener'); $('#navigation-options').hidden = true; }); $('#open-apple-maps').addEventListener('click', () => { const stop = nextStop(); if (stop) window.open(`https://maps.apple.com/?daddr=${stop.lat},${stop.lon}&dirflg=d`, '_blank', 'noopener'); $('#navigation-options').hidden = true; }); $('#open-waze').addEventListener('click', () => { const stop = nextStop(); if (stop) window.open(`https://waze.com/ul?ll=${stop.lat}%2C${stop.lon}&navigate=yes`, '_blank', 'noopener'); $('#navigation-options').hidden = true; });
document.addEventListener('click', (event) => { if (!event.target.closest('.navigation-actions')) $('#navigation-options').hidden = true; });
document.addEventListener('pointerdown', (event) => { if (!event.target.closest('.navigation-actions')) $('#navigation-options').hidden = true; });
window.addEventListener('touchstart', (event) => { if (!event.target.closest('.navigation-actions')) $('#navigation-options').hidden = true; }, { passive: true });
function toggleMobileRouteView() { const workspace = document.querySelector('.route-workspace'); const showingMap = !workspace.classList.contains('show-route-map'); workspace.classList.toggle('show-route-map', showingMap); $('#toggle-route-view-mobile').textContent = showingMap ? 'Înapoi la rută' : 'Vezi harta'; if (showingMap) setTimeout(() => { map.invalidateSize(); drawMap(); }, 150); }
$('#toggle-route-view-mobile').addEventListener('click', toggleMobileRouteView);
$('#map-back-to-list').addEventListener('click', toggleMobileRouteView);
$('#finish-job').addEventListener('click', () => { localStorage.removeItem(STORAGE_KEY); window.location.href = 'index.html'; }); $('#close-status-modal').addEventListener('click', () => { $('#delivery-status-modal').hidden = true; }); $('#save-delivery-status').addEventListener('click', saveStatusEditor);
renderList(); updateProgress(); drawMap(); setTimeout(() => map.invalidateSize(), 100);

window.addEventListener('blur', () => { $('#navigation-options').hidden = true; });
document.addEventListener('visibilitychange', () => { if (document.hidden) $('#navigation-options').hidden = true; });









