import { saveSnapshot, saveCompletedStop, getActiveSnapshot } from './storage.js';
const STORAGE_KEY = 'route-optimizer-romania-v1';
const COMPLETED_KEY = 'route-optimizer-completed-v1';
function cleanPoint(point) { if (!point || !Number.isFinite(Number(point.lat)) || !Number.isFinite(Number(point.lon))) return null; return { ...point, lat: Number(point.lat), lon: Number(point.lon), display_name: String(point.display_name || point.input || 'Adresă') }; }
function cleanStops(stops) { return Array.isArray(stops) ? stops.map(cleanPoint).filter(Boolean) : []; }
let saved = null;
try { saved = JSON.parse(localStorage.getItem(STORAGE_KEY) || 'null'); } catch { localStorage.removeItem(STORAGE_KEY); }
const state = saved || { start: null, end: null, stops: [], returnToStart: false };
state.start = cleanPoint(state.start); state.end = cleanPoint(state.end); state.stops = cleanStops(state.stops);
const map = L.map('route-map').setView([45.9432, 24.9668], 7);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; OpenStreetMap contributors' }).addTo(map);
const $ = (selector) => document.querySelector(selector);
function formatRouteDuration(seconds) { const minutes = Math.max(0, Math.round(Number(seconds || 0) / 60)); const hours = Math.floor(minutes / 60); const rest = minutes % 60; return hours ? `${hours} h${rest ? ` ${rest} min` : ''}` : `${rest} min`; }
function save() { try { localStorage.setItem(STORAGE_KEY, JSON.stringify(state)); } catch {} saveSnapshot(state); }
function pinIcon(color, label) { return L.divIcon({ className: 'pin-icon', html: `<svg viewBox="0 0 38 48" aria-hidden="true"><path d="M19 1C9.1 1 1.5 8.4 1.5 17.5 1.5 29.5 19 47 19 47s17.5-17.5 17.5-29.5C36.5 8.4 28.9 1 19 1Z" fill="${color}" stroke="#f3fffb" stroke-width="2"/><circle cx="19" cy="17" r="10" fill="#ffffff33"/><text x="19" y="21" text-anchor="middle" fill="#fff" font-size="11" font-weight="800" font-family="Arial, sans-serif">${label}</text></svg>`, iconSize: [38, 48], iconAnchor: [19, 47] }); }
function popupContent(label, point, status = '') { const box = document.createElement('div'); const title = document.createElement('strong'); title.textContent = label; const address = document.createElement('div'); address.textContent = point?.display_name || point?.input || ''; box.append(title, address); if (status) { const detail = document.createElement('small'); detail.textContent = status; box.append(detail); } return box; }
function renderList() { const list = $('#delivery-list'); list.replaceChildren(); const addText = (parent, tag, value, className = '') => { const node = document.createElement(tag); node.textContent = value || ''; if (className) node.className = className; parent.append(node); return node; }; state.stops.filter((stop) => !stop.delivered).forEach((stop) => { const item = document.createElement('li'); item.className = 'delivery-item'; const body = document.createElement('div'); const routeNumber = state.stops.indexOf(stop) + 1; addText(body, 'strong', `Stop ${routeNumber}`); const details = document.createElement('span'); addText(details, 'span', stop.display_name || stop.input || 'Adresă'); if (stop.etaLabel) addText(details, 'small', `Sosire estimată: ${stop.etaLabel}`, 'eta-label'); if (stop.statusLabel) { const statusKey = Object.prototype.hasOwnProperty.call(STATUS_LABELS, stop.status) ? stop.status : 'delivered'; addText(details, 'small', stop.statusLabel, `status-badge status-${statusKey}`); } if (stop.note) addText(details, 'small', `Notiță: ${stop.note}`); body.append(details); const button = document.createElement('button'); button.className = 'deliver-button'; button.dataset.index = String(routeNumber - 1); button.textContent = 'Marchează stop'; item.append(body, button); list.append(item); }); if (state.end || (state.returnToStart && state.start)) { const finish = document.createElement('li'); finish.className = 'delivery-item'; const body = document.createElement('div'); addText(body, 'strong', 'Finish'); const details = document.createElement('span'); addText(details, 'span', (state.end || state.start).display_name || (state.end || state.start).input || 'Adresă finală'); if ((state.end || state.start).etaLabel) addText(details, 'small', `Sosire estimată: ${(state.end || state.start).etaLabel}`, 'eta-label'); body.append(details); const button = document.createElement('button'); button.className = 'navigate-stop finish-navigation'; button.type = 'button'; button.textContent = 'Navighează'; finish.append(body, button); list.append(finish); } const delivered = state.stops.filter((stop) => stop.delivered).length; const metrics = []; if (state.routeDistance) metrics.push(`${(state.routeDistance / 1000).toFixed(1)} km`); if (state.routeDuration) metrics.push(formatRouteDuration(state.routeDuration)); $('#route-meta').textContent = `${state.stops.length} opriri · ${delivered} livrate${metrics.length ? ` · ${metrics.join(' · ')}` : ''}`; list.querySelectorAll('.deliver-button').forEach((button) => button.addEventListener('click', () => openStatusEditor(Number(button.dataset.index)))); const finishNavigation = list.querySelector('.finish-navigation'); if (finishNavigation) finishNavigation.addEventListener('click', () => openPreferredNavigation(state.end || state.start, preferredNavigation?.value || 'google')); }
const STATUS_LABELS = { delivered: 'Livrat', absent: 'Client absent', 'wrong-address': 'Adresă greșită', rescheduled: 'Reprogramat', cancelled: 'Anulat' };
function saveStatusEditor() { const modal = $('#delivery-status-modal'); const index = Number(modal.dataset.index); const stop = state.stops[index]; if (!stop) return; const status = $('#delivery-status').value; stop.status = status; stop.delivered = status === 'delivered'; stop.note = $('#delivery-note').value.trim(); stop.statusLabel = STATUS_LABELS[status]; stop.updatedAt = new Date().toISOString(); stop.actualServiceMinutes = stop.arrivalAt ? Math.max(0, Math.round((new Date(stop.updatedAt).getTime() - new Date(stop.arrivalAt).getTime()) / 60000)) : 0; if (stop.delivered) { stop.deliveredAt = stop.updatedAt; navigator.vibrate?.(35); } else { stop.deliveredAt = null; } const historyEvent = { ...stop, historyAt: stop.updatedAt }; let history = []; try { history = JSON.parse(localStorage.getItem(COMPLETED_KEY) || '[]'); if (!Array.isArray(history)) history = []; } catch {} history.push(historyEvent); saveCompletedStop(historyEvent); try { localStorage.setItem(COMPLETED_KEY, JSON.stringify(history)); } catch {} recalculateRemainingEta(); save(); modal.hidden = true; renderList(); updateProgress(); drawMap(); }function updateProgress() { const total = state.stops.length; const delivered = state.stops.filter((stop) => stop.delivered).length; const nextStop = state.stops.find((stop) => !stop.delivered); const finish = total > 0 && !nextStop && state.end ? { ...state.end, isFinish: true } : null; const next = nextStop || finish; $('#progress-label').textContent = `${delivered} / ${total} livrate`; $('#progress-percent').textContent = `${total ? Math.round((delivered / total) * 100) : 0}%`; $('#progress-bar').style.width = `${total ? (delivered / total) * 100 : 0}%`; $('#next-stop-card').hidden = !next; if (next) { const delay = Number(state.routeDelayMinutes || 0); $('#next-stop-address').textContent = `${next.display_name}${next.etaLabel ? ` · Sosire estimată ${next.etaLabel}` : ''}${delay > 0 ? ` · Întârziat cu ${delay} min` : ''}`; $('#next-label').textContent = next.isFinish ? 'FINISH' : 'URMĂTOAREA OPRIRE'; } $('#finish-job').hidden = !(total > 0 && delivered === total); }
let routeMarkers = []; let routeLine = null; let courierMarker = null; let courierAccuracyCircle = null; function drawMap() { routeMarkers.forEach((marker) => marker.remove()); routeMarkers = []; if (routeLine) { routeLine.remove(); routeLine = null; } if (state.start) { const marker = L.marker([state.start.lat, state.start.lon], { icon: pinIcon('#e08a20', 'S'), zIndexOffset: 1000 }).addTo(map); marker.bindPopup(popupContent('Start', state.start)); routeMarkers.push(marker); } state.stops.forEach((stop, index) => { const statusColor = stop.status === 'delivered' ? '#c84b63' : stop.status === 'absent' ? '#f0b55e' : stop.status === 'wrong-address' ? '#f08a9c' : stop.status === 'rescheduled' ? '#7b8fe8' : stop.status === 'cancelled' ? '#8a9a95' : '#0f8f7b'; const marker = L.marker([stop.lat, stop.lon], { icon: pinIcon(statusColor, index + 1) }).addTo(map); marker.bindPopup(popupContent(`Stop ${index + 1}`, stop, stop.statusLabel || 'Neprocesat')); routeMarkers.push(marker); }); const end = state.end || (state.returnToStart ? state.start : null); if (end) { const marker = L.marker([end.lat, end.lon], { icon: pinIcon('#c84b63', 'F'), zIndexOffset: 900 }).addTo(map); marker.bindPopup(popupContent('Finish', end)); routeMarkers.push(marker); } const points = [state.start, ...state.stops, end].filter(Boolean); if (points.length > 1) routeLine = state.routeGeometry ? L.geoJSON(state.routeGeometry, { style: { color: '#36b89b', weight: 5, opacity: .8 } }).addTo(map) : L.polyline(points.map((point) => [point.lat, point.lon]), { color: '#d08a28', weight: 4, opacity: .8, dashArray: '5 7' }).addTo(map); if (points.length > 1) map.fitBounds(L.latLngBounds(points.map((point) => [point.lat, point.lon])).pad(.1), { maxZoom: 16 }); else if (points.length === 1) map.setView([points[0].lat, points[0].lon], 15); }
$('#recalculate').addEventListener('click', () => { state.stops = state.stops.filter((stop) => !stop.delivered); save(); window.location.href = 'index.html?recalculate=1'; });
$('#reset-delivered').addEventListener('click', () => { if (!window.confirm('Resetezi toate livrările din ruta curentă?')) return; state.stops.forEach((stop) => { stop.delivered = false; stop.deliveredAt = null; stop.status = ''; stop.statusLabel = ''; stop.note = ''; stop.arrivalAt = null; stop.updatedAt = null; }); state.routeDelayMinutes = 0; state.routeDelayApplied = 0; save(); renderList(); updateProgress(); drawMap(); });
function nextStop() { const next = state.stops.find((stop) => !stop.delivered); return next || (state.end ? { ...state.end, isFinish: true } : null); }
const preferredNavigation = $('#preferred-navigation'); preferredNavigation.value = localStorage.getItem('route-optimizer-navigation') || 'ask'; preferredNavigation.addEventListener('change', () => localStorage.setItem('route-optimizer-navigation', preferredNavigation.value)); function openPreferredNavigation(stop, choice) { if (!stop) return; const url = choice === 'apple' ? `https://maps.apple.com/?daddr=${stop.lat},${stop.lon}&dirflg=d` : choice === 'waze' ? `https://waze.com/ul?ll=${stop.lat}%2C${stop.lon}&navigate=yes` : `https://www.google.com/maps/dir/?api=1&destination=${stop.lat},${stop.lon}`; const opened = window.open(url, '_blank', 'noopener'); if (!opened) { const copyPromise = navigator.clipboard?.writeText(stop.display_name || stop.input || ''); if (copyPromise) copyPromise.then(() => setStatus('Navigarea a fost blocată. Adresa a fost copiată.')).catch(() => setStatus('Navigarea a fost blocată. Copiază adresa manual.', true)); else setStatus('Navigarea a fost blocată. Copiază adresa manual.', true); } }
$('#navigate-next').addEventListener('click', () => { const choice = preferredNavigation.value; const stop = nextStop(); if (choice !== 'ask') { openPreferredNavigation(stop, choice); return; } $('#navigation-options').hidden = !$('#navigation-options').hidden; }); $('#open-google-maps').addEventListener('click', () => { openPreferredNavigation(nextStop(), 'google'); $('#navigation-options').hidden = true; }); $('#open-apple-maps').addEventListener('click', () => { openPreferredNavigation(nextStop(), 'apple'); $('#navigation-options').hidden = true; }); $('#open-waze').addEventListener('click', () => { openPreferredNavigation(nextStop(), 'waze'); $('#navigation-options').hidden = true; });
document.addEventListener('click', (event) => { if (!event.target.closest('.navigation-actions')) $('#navigation-options').hidden = true; });
document.addEventListener('pointerdown', (event) => { if (!event.target.closest('.navigation-actions')) $('#navigation-options').hidden = true; });
window.addEventListener('touchstart', (event) => { if (!event.target.closest('.navigation-actions')) $('#navigation-options').hidden = true; }, { passive: true });
function toggleMobileRouteView() { const workspace = document.querySelector('.route-workspace'); const showingMap = !workspace.classList.contains('show-route-map'); workspace.classList.toggle('show-route-map', showingMap); $('#toggle-route-view-mobile').textContent = showingMap ? 'Înapoi la rută' : 'Vezi harta'; if (showingMap) setTimeout(() => { map.invalidateSize(); drawMap(); }, 150); }
$('#toggle-route-view-mobile').addEventListener('click', toggleMobileRouteView);
$('#map-back-to-list').addEventListener('click', toggleMobileRouteView);
$('#finish-job').addEventListener('click', async () => { if (!window.confirm('Închei jobul și pornesc o rută nouă? Istoricul livrărilor rămâne salvat.')) return; localStorage.removeItem(STORAGE_KEY); await saveSnapshot({ start: null, end: null, stops: [], routeGeometry: null, routeDistance: 0, routeDuration: 0 }); window.location.href = 'index.html'; }); $('#close-status-modal').addEventListener('click', () => { $('#delivery-status-modal').hidden = true; }); $('#save-delivery-status').addEventListener('click', saveStatusEditor);
async function initializeRoutePage() { if (!state.start && !state.end && !state.stops.length) { const snapshot = await getActiveSnapshot(); const data = snapshot?.data; if (data && (data.start || data.end || data.stops?.length)) { Object.assign(state, data); state.start = cleanPoint(state.start); state.end = cleanPoint(state.end); state.stops = cleanStops(state.stops); setStatus('Ruta activă a fost restaurată automat'); } } recalculateRemainingEta(); save(); renderList(); updateProgress(); drawMap(); setTimeout(() => map.invalidateSize(), 100); } initializeRoutePage();

window.addEventListener('blur', () => { $('#navigation-options').hidden = true; });
document.addEventListener('visibilitychange', () => { if (document.hidden) $('#navigation-options').hidden = true; });










const courierLocationIcon = L.divIcon({ className: 'courier-location-icon', html: '<span></span>', iconSize: [22, 22], iconAnchor: [11, 11] });
let locationWatchId = null; let firstCourierFix = true; function updateCourierPosition({ coords }) { const point = [coords.latitude, coords.longitude]; if (!courierMarker) courierMarker = L.marker(point, { icon: courierLocationIcon, zIndexOffset: 2000 }).addTo(map); else courierMarker.setLatLng(point); const accuracy = Number(coords.accuracy || 0); if (accuracy > 0) { if (!courierAccuracyCircle) courierAccuracyCircle = L.circle(point, { radius: accuracy, color: '#36b89b', fillColor: '#36b89b', fillOpacity: .12, weight: 1 }).addTo(map); else courierAccuracyCircle.setLatLng(point).setRadius(accuracy); } if (firstCourierFix) { map.setView(point, Math.max(map.getZoom(), 15)); firstCourierFix = false; } }
function stopLocationWatch(message = '') { const button = $('#locate-courier'); if (locationWatchId !== null) navigator.geolocation.clearWatch(locationWatchId); locationWatchId = null; firstCourierFix = true; if (courierAccuracyCircle) { courierAccuracyCircle.remove(); courierAccuracyCircle = null; } if (button) { button.textContent = '◎ Locația mea'; button.title = message || 'Pornește urmărirea GPS'; } if (message) window.alert(message); }
function locateCourier() { const button = $('#locate-courier'); if (!navigator.geolocation) { stopLocationWatch('Browserul nu oferă localizare GPS.'); return; } if (locationWatchId !== null) { stopLocationWatch(); return; } button && (button.textContent = '■ Oprește urmărirea'); button && (button.title = 'Oprește urmărirea GPS'); const error = () => stopLocationWatch('Nu am putut obține locația. Verifică permisiunea GPS.'); navigator.geolocation.getCurrentPosition(updateCourierPosition, error, { enableHighAccuracy: true, timeout: 10000, maximumAge: 15000 }); locationWatchId = navigator.geolocation.watchPosition(updateCourierPosition, error, { enableHighAccuracy: true, maximumAge: 10000, timeout: 20000 }); }
$('#locate-courier')?.addEventListener('click', locateCourier);

let deliveryTimerInterval = null;
function openStatusEditor(index) { const stop = state.stops[index]; if (!stop) return; stop.arrivalAt = stop.arrivalAt || new Date().toISOString(); $('#delivery-status').value = stop.status || 'delivered'; $('#delivery-note').value = stop.note || ''; $('#delivery-status-modal').dataset.index = String(index); $('#delivery-status-modal').hidden = false; const timer = $('#delivery-timer'); const updateTimer = () => { const seconds = Math.max(0, Math.floor((Date.now() - new Date(stop.arrivalAt).getTime()) / 1000)); const minutes = Math.floor(seconds / 60); timer.textContent = `Timp la oprire: ${String(minutes).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}`; }; clearInterval(deliveryTimerInterval); updateTimer(); deliveryTimerInterval = setInterval(() => { if ($('#delivery-status-modal').hidden) { clearInterval(deliveryTimerInterval); return; } updateTimer(); }, 1000); $('#delivery-status').focus(); }
$('#close-status-modal').addEventListener('click', () => clearInterval(deliveryTimerInterval));

function addRouteBreak(minutes = 5) { const delta = minutes * 60000; state.stops.filter((stop) => !stop.delivered && stop.etaAt).forEach((stop) => { stop.etaAt += delta; stop.etaLabel = new Intl.DateTimeFormat('ro-RO', { hour: '2-digit', minute: '2-digit' }).format(new Date(stop.etaAt)); }); if (state.end?.etaAt) { state.end.etaAt += delta; state.end.etaLabel = new Intl.DateTimeFormat('ro-RO', { hour: '2-digit', minute: '2-digit' }).format(new Date(state.end.etaAt)); } save(); renderList(); updateProgress(); setStatus(`Pauză de ${minutes} minute adăugată`); }
$('#add-break')?.addEventListener('click', () => addRouteBreak(5));
$('#print-route')?.addEventListener('click', () => window.print());
document.querySelector('#share-route')?.addEventListener('click', async () => { const stops = state.stops.map((stop, index) => `${index + 1}. ${stop.display_name || stop.input || ''}${stop.etaLabel ? ` · ETA ${stop.etaLabel}` : ''}${stop.statusLabel ? ` · ${stop.statusLabel}` : ''}`); const finish = state.end ? `\nFinish: ${state.end.display_name || state.end.input || ''}${state.end.etaLabel ? ` · ETA ${state.end.etaLabel}` : ''}` : ''; const text = `Ruta curierului\n${stops.join('\n')}${finish}`; if (navigator.share) { try { await navigator.share({ title: 'Ruta curierului', text }); return; } catch (error) { if (error.name === 'AbortError') return; } } try { await navigator.clipboard.writeText(text); setStatus('Ruta a fost copiată pentru distribuire'); } catch { setStatus('Nu am putut distribui ruta.', true); } });

const deliveryListObserver = new MutationObserver(() => { const list = $('#delivery-list'); list?.querySelectorAll('.deliver-button').forEach((button) => { if (button.previousElementSibling?.classList.contains('navigate-stop')) return; const nav = document.createElement('button'); nav.className = 'navigate-stop'; nav.type = 'button'; nav.textContent = 'Navighează'; nav.dataset.index = button.dataset.index; nav.addEventListener('click', () => openPreferredNavigation(state.stops[Number(nav.dataset.index)], preferredNavigation?.value || 'ask')); button.parentElement ? button.parentElement.insertBefore(nav, button) : button.before(nav); }); });
deliveryListObserver.observe($('#delivery-list'), { childList: true, subtree: true });

// Show route delay consistently on active delivery items and Finish.
function recalculateRemainingEta() { const updatedStops = state.stops.filter((stop) => stop.updatedAt && stop.etaAt); if (!updatedStops.length) { state.routeDelayMinutes = 0; state.routeDelayApplied = 0; return; } const latest = updatedStops.reduce((a, b) => new Date(a.updatedAt) > new Date(b.updatedAt) ? a : b); const totalDelay = Math.max(0, Date.now() - new Date(latest.etaAt).getTime()); const previousDelay = Number(state.routeDelayApplied || 0); const delta = Math.max(0, totalDelay - previousDelay); state.routeDelayMinutes = Math.round(totalDelay / 60000); state.routeDelayApplied = totalDelay; if (!delta) return; state.stops.filter((stop) => !stop.delivered && stop.etaAt).forEach((stop) => { stop.etaAt += delta; stop.etaLabel = new Intl.DateTimeFormat('ro-RO', { hour: '2-digit', minute: '2-digit' }).format(new Date(stop.etaAt)); }); if (state.end?.etaAt) { state.end.etaAt += delta; state.end.etaLabel = new Intl.DateTimeFormat('ro-RO', { hour: '2-digit', minute: '2-digit' }).format(new Date(state.end.etaAt)); } }
function decorateRouteDelay() { const delay = Number(state.routeDelayMinutes || 0); document.querySelectorAll('#delivery-list .delivery-item > div > span').forEach((span) => { span.querySelector('.delay-label')?.remove(); if (delay > 0) { const label = document.createElement('small'); label.className = 'delay-label'; label.textContent = `Întârziat cu ${delay} min`; span.append(label); } }); const meta = document.querySelector('#route-meta'); if (meta && delay > 0 && !meta.textContent.includes('întârziere')) meta.textContent += ` · întârziere ${delay} min`; }
const delayObserver = new MutationObserver(() => decorateRouteDelay()); delayObserver.observe(document.querySelector('#delivery-list'), { childList: true, subtree: true });

$('#complete-next')?.addEventListener('click', () => { const stop = nextStop(); if (!stop || stop.isFinish) return; openStatusEditor(state.stops.indexOf(stop)); });


window.addEventListener('pagehide', () => { if (locationWatchId !== null && navigator.geolocation) navigator.geolocation.clearWatch(locationWatchId); });

function refreshLiveDelay() { const next = nextStop(); if (!next?.etaAt) return; const lateMinutes = Math.max(0, Math.round((Date.now() - Number(next.etaAt)) / 60000)); if (lateMinutes > Number(state.routeDelayMinutes || 0)) { state.routeDelayMinutes = lateMinutes; decorateRouteDelay(); updateProgress(); } }
window.setInterval(refreshLiveDelay, 30000);
