const PREF_KEY = 'route-optimizer-preferences-v1';
const ROUTE_KEY = 'route-optimizer-romania-v1';
const DB_NAME = 'route-optimizer-local-db';
const defaults = { navigation: 'ask', profile: 'car', capacity: 50, service: 0, traffic: 'auto' };
const $ = (selector) => document.querySelector(selector);
const status = (message, error = false) => { const node = $('#settings-status'); if (node) { node.textContent = message; node.style.background = error ? '#4a2525' : '#123b34'; node.style.color = error ? '#ffb4b4' : '#6ee7c8'; } };
function readPreferences() { try { return { ...defaults, ...(JSON.parse(localStorage.getItem(PREF_KEY) || '{}')) }; } catch { return { ...defaults }; } }
function writePreferences() { const data = { navigation: $('#setting-navigation').value, profile: $('#setting-profile').value, capacity: Math.max(1, Number($('#setting-capacity').value) || defaults.capacity), service: Math.max(0, Number($('#setting-service').value) || 0), traffic: $('#setting-traffic').value }; localStorage.setItem(PREF_KEY, JSON.stringify(data)); $('#setting-capacity').value = data.capacity; $('#setting-service').value = data.service; status('Preferințele au fost salvate'); }
function loadPreferences() { const data = readPreferences(); $('#setting-navigation').value = data.navigation; $('#setting-profile').value = data.profile; $('#setting-capacity').value = data.capacity; $('#setting-service').value = data.service; $('#setting-traffic').value = data.traffic; ['#setting-navigation', '#setting-profile', '#setting-capacity', '#setting-service', '#setting-traffic'].forEach((selector) => $(selector).addEventListener('change', writePreferences)); }
function download(name, content) { const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([content], { type: 'application/json' })); link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 500); }
$('#export-settings-backup').addEventListener('click', () => { const data = localStorage.getItem(ROUTE_KEY); if (!data) { status('Nu există o rută activă pentru backup.', true); return; } download(`route-optimizer-backup-${new Date().toISOString().slice(0, 10)}.json`, data); status('Backup descărcat'); });
$('#import-settings-backup').addEventListener('click', () => $('#settings-backup-file').click());
$('#settings-backup-file').addEventListener('change', async (event) => { const file = event.target.files[0]; if (!file) return; try { const data = JSON.parse(await file.text()); if (!data || !Array.isArray(data.stops)) throw new Error('Backup invalid.'); localStorage.setItem(ROUTE_KEY, JSON.stringify(data)); status('Backup încărcat. Deschid optimizarea…'); setTimeout(() => { window.location.href = 'index.html'; }, 500); } catch (error) { status(error.message || 'Backup invalid.', true); } event.target.value = ''; });
$('#clear-local-data').addEventListener('click', async () => { if (!window.confirm('Ștergi toate datele locale? Acțiunea nu poate fi anulată.')) return; localStorage.clear(); await new Promise((resolve) => { const request = indexedDB.deleteDatabase(DB_NAME); request.onsuccess = request.onerror = request.onblocked = () => resolve(); }); status('Date locale șterse'); });
async function renderDiagnostic() { const rows = [['Conexiune', navigator.onLine ? 'Online' : 'Offline'], ['GPS', 'geolocation' in navigator ? 'Disponibil în browser' : 'Indisponibil'], ['IndexedDB', 'indexedDB' in window ? 'Disponibil' : 'Indisponibil'], ['Service worker', 'serviceWorker' in navigator ? 'Disponibil' : 'Indisponibil'], ['OCR local', 'Resurse incluse în aplicație'], ['Salvare persistentă', 'persist' in navigator.storage ? 'Disponibilă' : 'Standard browser']]; const list = $('#diagnostic-list'); list.replaceChildren(); rows.forEach(([label, value]) => { const term = document.createElement('dt'); term.textContent = label; const desc = document.createElement('dd'); desc.textContent = value; list.append(term, desc); }); }
$('#refresh-diagnostic').addEventListener('click', renderDiagnostic); loadPreferences(); renderDiagnostic();
