const DB_NAME = 'route-optimizer-local-db';
const STORE_NAME = 'route-snapshots';
function openDatabase() { return new Promise((resolve, reject) => { const request = indexedDB.open(DB_NAME, 1); request.onupgradeneeded = () => request.result.createObjectStore(STORE_NAME, { keyPath: 'id' }); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); }
function putRecord(record) { return openDatabase().then((db) => new Promise((resolve, reject) => { const tx = db.transaction(STORE_NAME, 'readwrite'); tx.objectStore(STORE_NAME).put(record); tx.oncomplete = resolve; tx.onerror = () => reject(tx.error); })); }
export async function saveSnapshot(data) { try { const savedAt = new Date().toISOString(); await putRecord({ id: 'active-route', savedAt, data }); const day = savedAt.slice(0, 10); await putRecord({ id: `daily-${day}`, name: `Checkpoint ${day}`, savedAt, data }); } catch { /* localStorage rămâne fallback */ } }
export async function saveNamedRoute(name, data) { try { await putRecord({ id: `route-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`, name, savedAt: new Date().toISOString(), data }); } catch {} }
export async function listSavedRoutes() { try { const db = await openDatabase(); return await new Promise((resolve, reject) => { const request = db.transaction(STORE_NAME).objectStore(STORE_NAME).getAll(); request.onsuccess = () => resolve((request.result || []).filter((route) => route.id !== 'active-route' && route.name)); request.onerror = () => reject(request.error); }); } catch { return []; } }
export async function deleteSavedRoute(id) { if (!id) return; try { const db = await openDatabase(); await new Promise((resolve, reject) => { const tx = db.transaction(STORE_NAME, 'readwrite'); tx.objectStore(STORE_NAME).delete(id); tx.oncomplete = resolve; tx.onerror = () => reject(tx.error); }); } catch {} }
export async function saveCompletedStop(stop) { try { const db = await openDatabase(); const existing = await new Promise((resolve, reject) => { const request = db.transaction(STORE_NAME).objectStore(STORE_NAME).get('completed-history'); request.onsuccess = () => resolve(request.result?.items || []); request.onerror = () => reject(request.error); }); await putRecord({ id: 'completed-history', savedAt: new Date().toISOString(), items: [...existing, stop] }); } catch {} }
export async function listCompletedStops() { try { const db = await openDatabase(); return await new Promise((resolve, reject) => { const request = db.transaction(STORE_NAME).objectStore(STORE_NAME).get('completed-history'); request.onsuccess = () => resolve(request.result?.items || []); request.onerror = () => reject(request.error); }); } catch { return []; } }
export async function clearCompletedStops() { try { const db = await openDatabase(); await new Promise((resolve, reject) => { const tx = db.transaction(STORE_NAME, 'readwrite'); tx.objectStore(STORE_NAME).delete('completed-history'); tx.oncomplete = resolve; tx.onerror = () => reject(tx.error); }); } catch {} }
