const DB_NAME = 'route-optimizer-local-db';
const STORE_NAME = 'route-snapshots';
let writeQueue = Promise.resolve();
function openDatabase() { return new Promise((resolve, reject) => { const request = indexedDB.open(DB_NAME, 1); request.onupgradeneeded = () => request.result.createObjectStore(STORE_NAME, { keyPath: 'id' }); request.onsuccess = () => resolve(request.result); request.onerror = () => reject(request.error); }); }
function writeRecord(record) { return openDatabase().then((db) => new Promise((resolve, reject) => { const tx = db.transaction(STORE_NAME, 'readwrite'); tx.objectStore(STORE_NAME).put(record); tx.oncomplete = () => { db.close(); resolve(); }; tx.onerror = () => { db.close(); reject(tx.error); }; })); }
function enqueueWrite(task) { const run = writeQueue.then(task, task); writeQueue = run.catch(() => {}); return run; }
function putRecord(record) { return enqueueWrite(() => writeRecord(record)); }
export async function saveSnapshot(data) { try { const savedAt = new Date().toISOString(); await putRecord({ id: 'active-route', savedAt, data }); if (!data?.start && !data?.end && !data?.stops?.length) return; const day = savedAt.slice(0, 10); await putRecord({ id: `daily-${day}`, name: `Checkpoint ${day}`, savedAt, data }); } catch { /* localStorage rămâne fallback */ } }
export async function getActiveSnapshot() { try { const db = await openDatabase(); return await new Promise((resolve, reject) => { const request = db.transaction(STORE_NAME).objectStore(STORE_NAME).get('active-route'); request.onsuccess = () => { const result = request.result || null; db.close(); resolve(result); }; request.onerror = () => { db.close(); reject(request.error); }; }); } catch { return null; } }
export async function saveNamedRoute(name, data) { try { await putRecord({ id: `route-${Date.now()}-${Math.random().toString(36).slice(2, 7)}`, name, savedAt: new Date().toISOString(), data }); } catch {} }
export async function listSavedRoutes() { try { const db = await openDatabase(); return await new Promise((resolve, reject) => { const request = db.transaction(STORE_NAME).objectStore(STORE_NAME).getAll(); request.onsuccess = () => { const routes = (request.result || []).filter((route) => route.id !== 'active-route' && route.name); db.close(); resolve(routes); }; request.onerror = () => { db.close(); reject(request.error); }; }); } catch { return []; } }
export async function deleteSavedRoute(id) { if (!id) return; try { await enqueueWrite(() => openDatabase().then((db) => new Promise((resolve, reject) => { const tx = db.transaction(STORE_NAME, 'readwrite'); tx.objectStore(STORE_NAME).delete(id); tx.oncomplete = () => { db.close(); resolve(); }; tx.onerror = () => { db.close(); reject(tx.error); }; }))); } catch {} }
export async function saveCompletedStop(stop) { try { await enqueueWrite(async () => { const db = await openDatabase(); const existing = await new Promise((resolve, reject) => { const request = db.transaction(STORE_NAME).objectStore(STORE_NAME).get('completed-history'); request.onsuccess = () => { const items = request.result?.items || []; db.close(); resolve(items); }; request.onerror = () => { db.close(); reject(request.error); } }); const items = stop?.historyKey ? [...existing.filter((item) => item.historyKey !== stop.historyKey), stop] : [...existing, stop]; await writeRecord({ id: 'completed-history', savedAt: new Date().toISOString(), items }); }); } catch {} }
export async function listCompletedStops() { try { const db = await openDatabase(); return await new Promise((resolve, reject) => { const request = db.transaction(STORE_NAME).objectStore(STORE_NAME).get('completed-history'); request.onsuccess = () => { const items = request.result?.items || []; db.close(); resolve(items); }; request.onerror = () => { db.close(); reject(request.error); } }); } catch { return []; } }
export async function clearCompletedStops() { try { await enqueueWrite(() => openDatabase().then((db) => new Promise((resolve, reject) => { const tx = db.transaction(STORE_NAME, 'readwrite'); tx.objectStore(STORE_NAME).delete('completed-history'); tx.oncomplete = () => { db.close(); resolve(); }; tx.onerror = () => { db.close(); reject(tx.error); }; }))); } catch {} }


